name: interface
package: interface
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_interface
export_command: '/interface export'
resource_class_name: InterfaceResource
documentation:
  module: ros_interface
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Interface Resource Module'
  description:
    - 'This module manages the interface configuration of Mikrotik RouterOS network devices.'
  supports:
    - export-verbose-mode
  options:
    state:
      choices:
        - merged
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        disabled:
          type: bool
          default: 'False'
          description: 'Set interface disability.'
        l2mtu:
          type: str
        mtu:
          type: str
examples:
  - title: 'Using Merged'
    name: 'Merge configuration with device configuration'
    argument_spec:
      config:
        - name: ether2
          comment: 'ether2 updated'
          mtu: '2000'
        - name: ether3
          comment: 'ether3 updated'
          disabled: 'no'
          mtu: '3000'
      state: merged
    before: |
      /interface
      set comment="ether2 comment" default-name=ether2 mtu=1500
      set comment="ether3 comment" default-name=ether3 disabled=yes mtu=1500
    after: |
      # RouterOS Output
      #
      /interface
      add comment="ether2 updated" mtu=2000 name=ether2
      add comment="ether3 updated" disabled=no mtu=3000 name=ether3
    commands:
      - '/interface set [ find name=ether2 ] comment="ether2 updated" mtu=2000'
      - '/interface set [ find name=ether3 ] comment="ether3 updated" disabled=no mtu=3000'
resource:
  name: interface
  package: interface
  command: /interface
  config_type: config
  keys:
    - name
  supports:
    - export-verbose-mode
  argument_spec:
    states:
      type: str
      choices:
        - merged
      default: merged
    config:
      type: list
      elements: dict
      options:
        disabled:
          type: bool
          default: 'False'
        l2mtu:
          type: str
        mtu:
          type: str
        comment:
          type: str
        default_name:
          type: str
        name:
          type: str
          required: 'True'
tests:
  facts:
    name: interface
    fixture_contents: |
      # RouterOS Output
      #
      /interface
      add comment="ether2 comment" default-name=ether2 mtu=1500
      add comment="ether3 comment" default-name=ether3 disabled=yes mtu=1500
    fixtures:
      - action: set
        values:
          comment: 'ether2 comment'
          default_name: ether2
          mtu: '1500'
      - action: set
        values:
          comment: 'ether3 comment'
          default_name: ether3
          disabled: 'yes'
          mtu: '1500'
  unit:
    module_name: ros_interface
    fixture_contents: |
      # RouterOS Output
      #
      /interface
      add comment="ether2 comment" default-name=ether2 mtu=1500
      add comment="ether3 comment" default-name=ether3 disabled=yes mtu=1500
    tests:
      - commands:
          - '/interface set [ find name=ether2 ] comment="ether2 updated" mtu=2000'
          - '/interface set [ find name=ether3 ] comment="ether3 updated" disabled=no mtu=3000'
        argument_spec:
          config: [{ comment: 'ether2 updated', mtu: '2000', name: ether2 }, { comment: 'ether3 updated', disabled: 'no', mtu: '3000', name: ether3 }]
          state: merged
