name: ethernet
package: interface
type: config
command: '/interface ethernet'
keys:
  - name
properties:
  advertise:
    name: advertise
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: advertise
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set interface disability.'
    original_name: disabled
