name: interface
package: interface
type: config
command: /interface
keys:
  - name
properties:
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set interface disability.'
    original_name: disabled
  l2mtu:
    name: l2mtu
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: l2mtu
  mtu:
    name: mtu
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: mtu
