name: vlan
package: interface
type: config
command: '/interface vlan'
keys:
  - name
properties:
  interface:
    name: interface
    type: null
    required: true
    default: null
    choice_type: null
    description: null
    original_name: interface
  vlan_id:
    name: vlan_id
    type: null
    required: true
    default: null
    choice_type: null
    description: null
    original_name: vlan-id
