doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        driver: 'pdo_sqlite'
        options:
            'PRAGMA foreign_keys': 'ON'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            RouterOS:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model'
                prefix: 'RouterOS\Generator\Model'
                alias: RouterOS
            Ansible:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Provider/Ansible/Model'
                prefix: 'RouterOS\Generator\Provider\Ansible\Model'
                alias: RouterOS
