twig:
  paths:
      "%kernel.project_dir%/etc/ansible/templates": "ansible"

routeros:
  config_dir: "%kernel.project_dir%/etc"
  compiled_dir: "%kernel.project_dir%/config/compiled"
  cache_dir: "%kernel.project_dir%/var/cache/routeros"
  ansible:
    git_repository: "https://github.com/kilip/ansible-collection-routeros.git"
    module_name_prefix: "kilip.routeros"
    target_dir: "%kernel.project_dir%/var/ansible_collections/kilip/routeros"