twig:
  paths:
      "%kernel.project_dir%/etc/ansible/templates": "ansible"

routeros:
  config_dir: "%kernel.project_dir%/etc"
  compiled_dir: "%kernel.project_dir%/config/compiled"
  cache_dir: "%kernel.project_dir%/var/cache/routeros"
  ansible:
    default_author: "%env(resolve:AUTHOR)%"
    module_prefix: "ros_"
    module_full_prefix: "kilip.routeros"
    target_dir: "%kernel.project_dir%/var/ansible_collections/kilip/routeros"
    git:
      repository: "https://github.com/kilip/ansible-routeros-collection.git"
      branch: wip
