name: capsman_configuration
package: capsman
type: config
command: '/caps-man configuration'
keys:
  - name
properties:
  channel:
    name: channel
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: channel
  channel_width:
    name: channel_width
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: channel-width
  datapath:
    name: datapath
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: datapath
  datapath_bridge:
    name: datapath_bridge
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: datapath-bridge
  datapath_interface_list:
    name: datapath_interface_list
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: datapath-interface-list
  datapath_l2mtu:
    name: datapath_l2mtu
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: datapath-l2mtu
  datapath_mtu:
    name: datapath_mtu
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: datapath-mtu
  datapath_openflow_switch:
    name: datapath_openflow_switch
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: datapath-openflow-switch
  disconnect_timeout:
    name: disconnect_timeout
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: disconnect-timeout
  distance:
    name: distance
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: distance
  frame_lifetime:
    name: frame_lifetime
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: frame-lifetime
  hw_protection_mode:
    name: hw_protection_mode
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: hw-protection-mode
  hw_retries:
    name: hw_retries
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: hw-retries
  mode:
    name: mode
    type: string
    required: false
    default: ap
    choice_type: null
    description: null
    original_name: mode
  rates:
    name: rates
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: rates
  rx_chains:
    name: rx_chains
    type: list
    required: false
    default:
      - 0
    choices:
      - 0
      - 1
      - 2
      - 3
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: rx-chains
  security_authentication_types:
    name: security_authentication_types
    type: list
    required: false
    default: null
    choices:
      - wpa-psk
      - wpa2-psk
      - wpa-eap
      - wpa2-eap
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: security-authentication-types
  security_disable_pmkid:
    name: security_disable_pmkid
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: security-disable-pmkid
  security_eap_radius_accounting:
    name: security_eap_radius_accounting
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: security-eap-radius-accounting
  security_encryption:
    name: security_encryption
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: security-encryption
  tx_chains:
    name: tx_chains
    type: list
    required: false
    default:
      - 0
    choices:
      - 0
      - 1
      - 2
      - 3
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: tx-chains
