name: capsman_provisioning
package: capsman
type: config
command: '/caps-man provisioning'
keys:
  - comment
properties:
  action:
    name: action
    type: string
    required: false
    default: none
    choices:
      - create-disabled
      - create-dynamic-enabled
      - create-enabled
      - none
    choice_type: null
    description: |
      Action to take if rule matches are specified by the following settings:
      
      - **create-disabled** - create disabled static interfaces for radio. I.e., the interfaces will be bound to the radio, but the radio will not be operational until the interface is manually enabled;
      - **create-enabled** - create enabled static interfaces. I.e., the interfaces will be bound to the radio and the radio will be operational;
      - **create-dynamic-enabled** - create enabled dynamic interfaces. I.e., the interfaces will be bound to the radio, and the radio will be operational;
      - **none** - do nothing, leaves radio in non-provisioned state;
    original_name: action
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short description of the Provisioning rule'
    original_name: comment
  common_name_regexp:
    name: common_name_regexp
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Regular expression to match radios by common name. Each CAP''s common name identifier can be found under "/caps-man radio" as value "REMOTE-CAP-NAME"'
    original_name: common-name-regexp
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set capsman_provisioning resource disability'
    original_name: disabled
  hw_supported_modes:
    name: hw_supported_modes
    type: string
    required: false
    default: null
    choices:
      - a
      - a-turbo
      - ac
      - an
      - b
      - g
      - g-turbo
      - gn
    choice_type: null
    description: 'Match radios by supported wireless modes'
    original_name: hw-supported-modes
  identity_regexp:
    name: identity_regexp
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Regular expression to match radios by router identity'
    original_name: identity-regexp
  ip_address_ranges:
    name: ip_address_ranges
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Match CAPs with IPs within configured address range.'
    options:
      - ignore-choices
      - ignore-default
    original_name: ip-address-ranges
  master_configuration:
    name: master_configuration
    type: string
    required: false
    default: null
    choice_type: null
    description: 'If **action** specifies to create interfaces, then a new master interface with its configuration set to this configuration profile will be created'
    original_name: master-configuration
  name_format:
    name: name_format
    type: string
    required: false
    default: cap
    choices:
      - cap
      - identity
      - prefix
      - prefix-identity
    choice_type: null
    description: |
      specify the syntax of the CAP interface name creation
      
      - cap - default name
      - identity - CAP boards system identity name
      - prefix - name from the name-prefix value
      - prefix-identity - name from the name-prefix value and the CAP boards system identity name
    original_name: name-format
  name_prefix:
    name: name_prefix
    type: string
    required: false
    default: null
    choice_type: null
    description: 'name prefix which can be used in the name-format for creating the CAP interface names'
    original_name: name-prefix
  radio_mac:
    name: radio_mac
    type: string
    required: false
    default: '00:00:00:00:00:00'
    choice_type: null
    description: 'MAC address of radio to be matched, empty MAC (00:00:00:00:00:00) means match all MAC addresses'
    original_name: radio-mac
  slave_configurations:
    name: slave_configurations
    type: list
    required: false
    default: null
    choice_type: null
    description: 'If **action** specifies to create interfaces, then a new slave interface for each configuration profile in this list is created.'
    original_name: slave-configurations
