name: capsman_aaa
package: capsman
type: setting
command: '/caps-man aaa'
keys:
  - name
properties:
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short note for capsman_aaa resource'
    original_name: comment
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set capsman_aaa resource disability'
    original_name: disabled
  interim_update:
    name: interim_update
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-choices
    original_name: interim-update
  mac_caching:
    name: mac_caching
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-choices
    original_name: mac-caching
