name: capsman_channel
package: capsman
type: config
command: '/caps-man channel'
keys:
  - name
properties:
  save_selected:
    name: save_selected
    type: string
    required: false
    default: null
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: null
    original_name: save-selected
  width:
    name: width
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: width
