name: capsman_provisioning
package: capsman
type: config
command: '/caps-man provisioning'
keys:
  - comment
properties:
  ip_address_ranges:
    name: ip_address_ranges
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-choices
      - ignore-default
    original_name: ip-address-ranges
  slave_configurations:
    name: slave_configurations
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: slave-configurations
