name: capsman_channel
package: capsman
type: config
command: '/caps-man channel'
keys:
  - name
properties:
  band:
    name: band
    type: string
    required: false
    default: null
    choices:
      - 2ghz-b
      - 2ghz-b/g
      - 2ghz-b/g/n
      - 2ghz-onlyg
      - 2ghz-onlyn
      - 5ghz-a
      - 5ghz-a/n
      - 5ghz-onlyn
    choice_type: null
    description: 'Define operational radio frequency band and mode taken from hardware capability of wireless card'
    original_name: band
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short description of the Channel Group profile'
    original_name: comment
  extension_channel:
    name: extension_channel
    type: string
    required: false
    default: null
    choices:
      - Ce
      - Ceee
      - disabled
      - eC
      - eCee
      - eeCe
      - eeeC
    choice_type: null
    description: 'Extension channel configuration. (E.g. Ce = extension channel is above Control channel, eC = extension channel is below Control channel)'
    original_name: extension-channel
  frequency:
    name: frequency
    type: integer
    required: false
    default: null
    choice_type: null
    description: 'Channel frequency value in MHz on which AP will operate.'
    original_name: frequency
  name:
    name: name
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Descriptive name for the Channel Group Profile'
    original_name: name
  save_selected:
    name: save_selected
    type: string
    required: false
    default: 'yes'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Saves selected channel for the CAP Radio - will select this channel after the CAP reconnects to CAPsMAN and use it till the channel Re-optimize is done for this CAP.'
    original_name: save-selected
  tx_power:
    name: tx_power
    type: integer
    required: false
    default: null
    choice_type: null
    description: 'TX Power for CAP interface (for the whole interface not for individual chains) in dBm. It is not possible to set higher than allowed by country regulations or interface. By default max allowed by country or interface is used.'
    original_name: tx-power
  width:
    name: width
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Sets Channel Width in MHz. (E.g. 20, 40)'
    original_name: width
