name: capsman_manager
package: capsman
type: setting
command: '/caps-man manager'
keys:
  - name
properties:
  ca_certificate:
    name: ca_certificate
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-choices
    original_name: ca-certificate
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short note for capsman_manager resource'
    original_name: comment
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set capsman_manager resource disability'
    original_name: disabled
