name: capsman_datapath
package: capsman
type: config
command: '/caps-man datapath'
keys:
  - name
properties:
  arp:
    name: arp
    type: string
    required: false
    default: enabled
    choices:
      - disabled
      - enabled
      - proxy-arp
      - reply-only
    choice_type: null
    description: |
      Address Resolution Protocol setting
      - `disabled` - the interface will not use ARP
      - `enabled` - the interface will use ARP
      - `proxy-arp` - the interface will use the ARP proxy feature
      - `reply-only` - the interface will only reply to requests originated from matching IP address/MAC address combinations which are entered as static entries in the L(IP/ARP,https://wiki.mikrotik.com/wiki/Manual:IP/ARP) table. Therefore for communications to be successful, a valid static entry must already exist.
      
    original_name: arp
  bridge:
    name: bridge
    type: string
    required: false
    default: null
    choice_type: null
    description: |
      Bridge to which particular interface should be automatically added as port. Required only when local-forwarding is not used.
      
    original_name: bridge
  bridge_cost:
    name: bridge_cost
    type: integer
    required: false
    default: null
    choice_type: null
    description: |
      bridge port cost to use when adding as bridge port
      
    original_name: bridge-cost
  bridge_horizon:
    name: bridge_horizon
    type: integer
    required: false
    default: null
    choice_type: null
    description: |
      bridge horizon to use when adding as bridge port
      
    original_name: bridge-horizon
  client_to_client_forwarding:
    name: client_to_client_forwarding
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: |
      controls if client-to-client forwarding between wireless clients connected to interface should be allowed, in local forwarding mode this function is performed by CAP, otherwise it is performed by CAPsMAN
      
    original_name: client-to-client-forwarding
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short description of the datapath'
    original_name: comment
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set capsman_datapath resource disability'
    original_name: disabled
  interface_list:
    name: interface_list
    type: list
    required: false
    default: null
    choice_type: null
    description: 'interface list for this datapath'
    original_name: interface-list
  l2mtu:
    name: l2mtu
    type: string
    required: false
    default: null
    choice_type: null
    description: 'set Layer2 MTU size'
    original_name: l2mtu
  local_forwarding:
    name: local_forwarding
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: |
      Controls forwarding mode. If disabled, all L2 and L3 data will be forwarded to CAPsMAN, and further forwarding decisions will be made only then.
      Note, if disabled, make sure that each CAP interface MAC Address that participates in the same broadcast domain is unique (including local MACs, like Bridge-MAC).
      
    original_name: local-forwarding
  mtu:
    name: mtu
    type: string
    required: false
    default: null
    choice_type: null
    description: 'set MTU size'
    original_name: mtu
  name:
    name: name
    type: string
    required: true
    default: null
    choice_type: null
    description: 'Name for datapath'
    original_name: name
  openflow_switch:
    name: openflow_switch
    type: string
    required: false
    default: null
    choice_type: null
    description: |
      OpenFlow switch port (when enabled) to add interface to
      
    original_name: openflow-switch
  vlan_id:
    name: vlan_id
    type: integer
    required: false
    default: null
    choice_type: null
    description: |
      VLAN ID to assign to interface if vlan-mode enables use of VLAN tagging
      
    original_name: vlan-id
  vlan_mode:
    name: vlan_mode
    type: string
    required: false
    default: null
    choices:
      - use-service-tag
      - use-tag
    choice_type: null
    description: |
      Enables and specifies the type of VLAN tag to be assigned to the interface (causes all received data to get tagged with VLAN tag and allows the interface to only send out data tagged with given tag)
      
    original_name: vlan-mode
