name: bridge_port
package: interface.bridge
validated: true
command: '/interface bridge port'
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:Interface/Bridge'
  table_index: 2
properties:
  disabled:
    type: str
    choices:
      - 'yes'
      - 'no'
    description: 'Set bridge port disability'
    defaultValue: 'no'
