name: wireless_cap
package: interface.wireless
command: '/interface wireless cap'

type: setting
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:CAPsMAN'
  table_index: 0
properties:
  bridge:
    type: str
  interfaces:
    type: list
  discovery_interfaces:
    type: list
  caps_man_addresses:
    type: list
  caps_man_names:
    type: list
  caps_man_certificate_common_names:
    type: list
  static_virtual:
    type: str
    choices:
      - 'yes'
      - 'no'
    defaultValue: 'no'
  certificate:
    options:
      - ignore-choices
