name: wireless_access_list
package: interface.wireless
validated: true
command: '/interface wireless access-list'
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:Interface/Wireless'
  table_index: 4
properties:
  signal_range:
    type: str
    defaultValue: '-120..120'
  management_protection_key:
    options:
      - ignore-default
  private_key:
    options:
      - ignore-default
  private_pre_shared_key:
    options:
      - ignore-default
  time:
    type: str
    options:
      - ignore-choices
