name: wireless_cap
package: interface.wireless
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_wireless_cap
export_command: '/interface wireless cap export'
resource_class_name: WirelessCapResource
documentation:
  module: ros_wireless_cap
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Wireless CAP Setting'
  description:
    - 'This module manages the Wireless CAP setting of Mikrotik RouterOS network devices.'
  supports:
    - export-verbose-mode
  options:
    state:
      choices:
        - present
        - reset
      default: present
      description: 'Set state for this module'
    config:
      type: dict
      suboptions:
        bridge:
          type: str
        caps_man_addresses:
          type: list
        caps_man_certificate_common_names:
          type: list
        caps_man_names:
          type: list
        certificate:
          type: str
        comment:
          type: str
          description: 'Short note for wireless_cap resource'
        disabled:
          type: bool
          default: 'False'
          description: 'Set wireless_cap resource disability'
        discovery_interfaces:
          type: list
        interfaces:
          type: list
        static_virtual:
          type: bool
          default: 'False'
examples:
  - title: 'Change Wireless CAP Setting'
    name: 'Configure Wireless CAP'
    argument_spec:
      config:
        interfaces:
          - wlan1
          - wlan2
      state: present
    before: |
      /interface wireless cap
      set bridge=none caps-man-addresses="" caps-man-certificate-common-names="" caps-man-names="" certificate=none enabled=no lock-to-caps-man=no static-virtual=no
    after: |
      # 2020-09-16
      #
      /interface wireless cap
      set interfaces=wlan1,wlan2
    commands:
      - '/interface wireless cap set interfaces=wlan1,wlan2'
resource:
  name: wireless_cap
  package: interface.wireless
  command: '/interface wireless cap'
  config_type: setting
  keys:
    - name
  supports:
    - export-verbose-mode
  argument_spec:
    states:
      type: str
      choices:
        - present
        - reset
      default: present
    config:
      type: dict
      options:
        bridge:
          type: str
        caps_man_addresses:
          type: list
        caps_man_certificate_common_names:
          type: list
        caps_man_names:
          type: list
        certificate:
          type: str
        comment:
          type: str
        disabled:
          type: bool
          default: 'False'
        discovery_interfaces:
          type: list
        interfaces:
          type: list
        static_virtual:
          type: bool
          default: 'False'
        enabled:
          type: str
        lock_to_caps_man:
          type: str
tests:
  facts:
    name: wireless_cap
    fixture_contents: |
      # 2020-09-16
      #
      /interface wireless cap
      set bridge=none caps-man-addresses="" caps-man-certificate-common-names="" caps-man-names="" certificate=none enabled=no lock-to-caps-man=no static-virtual=no
    fixtures:
      - action: set
        values:
          bridge: none
          caps_man_addresses: '" caps-man-certificate-common-names="" caps-man-names="'
          certificate: none
          discovery_interfaces: ''
          enabled: 'no'
          interfaces: ''
          lock_to_caps_man: 'no'
          static_virtual: 'no'
  unit:
    module_name: ros_wireless_cap
    fixture_contents: |
      # 2020-09-16
      #
      /interface wireless cap
      set bridge=none caps-man-addresses="" caps-man-certificate-common-names="" caps-man-names="" certificate=none enabled=no lock-to-caps-man=no static-virtual=no
    tests:
      - commands:
          - '/interface wireless cap set interfaces=wlan1,wlan2'
        argument_spec:
          config: { interfaces: [wlan1, wlan2] }
          state: present
