name: wireless
package: interface.wireless
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_wireless
export_command: '/interface wireless export'
resource_class_name: WirelessResource
documentation:
  module: ros_wireless
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Wireless Resource Module'
  description:
    - 'This module manages the Wireless configuration of Mikrotik RouterOS network devices.'
  options:
    state:
      choices:
        - merged
        - replaced
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        ampdu_priorities:
          type: list
          choices: [0, 1, 2, 3, 4, 5, 6, 7]
          default: [0]
        disconnect_timeout:
          type: str
        radio_name:
          type: str
        rx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        scan_list:
          type: list
          default: [default]
        ssid:
          type: str
        tx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        update_stats_interval:
          type: str
        wps_mode:
          type: str
examples:
  - title: 'Using merged state'
    name: 'Merge device configuration'
    argument_spec:
      config:
        - name: wlan1
          comment: 'updated comment'
          ampdu_priorities: '0,1,2'
          supported_rates_ag: '6Mbps,24Mbps'
      state: merged
    before: |
      /interface wireless
      set comment="wlan1 comment" default-name=wlan1 security-profile=to-olympus
    after: |
      # RouterOS Output
      #
      /interface wireless
      add ampdu-priorities=0,1,2 comment="updated comment" name=wlan1 security-profile=default supported-rates-ag=6Mbps,24Mbps
    commands:
      - '/interface wireless set [ find name=wlan1 ] ampdu-priorities=0,1,2 comment="updated comment" security-profile=default supported-rates-ag=6Mbps,24Mbps'
  - title: 'Using replaced state'
    name: 'Replace device wireless configuration'
    argument_spec:
      config:
        - name: wlan1
          comment: 'new olympus'
          ssid: Olympus
          security_profile: new-olympus
      state: replaced
    before: |
      /interface wireless
      set comment="wlan1 comment" default-name=wlan1 security-profile=to-olympus
    after: |
      # RouterOS Output
      #
      /interface wireless
      add comment="new olympus" name=wlan1 security-profile=new-olympus ssid=Olympus
    commands:
      - '/interface wireless set [ find name=wlan1 ] comment="new olympus" security-profile=new-olympus ssid=Olympus'
resource:
  name: wireless
  package: interface.wireless
  command: '/interface wireless'
  config_type: config
  keys:
    - name
  argument_spec:
    states:
      type: str
      choices:
        - merged
        - replaced
      default: merged
    config:
      type: list
      elements: dict
      options:
        ampdu_priorities:
          type: list
          choices: [0, 1, 2, 3, 4, 5, 6, 7]
          default: [0]
        disconnect_timeout:
          type: str
        radio_name:
          type: str
        rx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        scan_list:
          type: list
          default: [default]
        ssid:
          type: str
        tx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        update_stats_interval:
          type: str
        wps_mode:
          type: str
        comment:
          type: str
        default_name:
          type: str
        security_profile:
          type: str
        name:
          type: str
          required: 'True'
        supported_rates_ag:
          type: str
tests:
  facts:
    name: wireless
    fixture_contents: |
      # RouterOS Output
      #
      /interface wireless
      add comment="wlan1 comment" default-name=wlan1 security-profile=to-olympus
    fixtures:
      - action: set
        values:
          comment: 'wlan1 comment'
          default_name: wlan1
          security_profile: to-olympus
  unit:
    module_name: ros_wireless
    fixture_contents: |
      # RouterOS Output
      #
      /interface wireless
      add comment="wlan1 comment" default-name=wlan1 security-profile=to-olympus
    tests:
      - commands:
          - '/interface wireless set [ find name=wlan1 ] ampdu-priorities=0,1,2 comment="updated comment" security-profile=default supported-rates-ag=6Mbps,24Mbps'
        argument_spec:
          config: [{ ampdu_priorities: '0,1,2', comment: 'updated comment', name: wlan1, supported_rates_ag: '6Mbps,24Mbps' }]
          state: merged
      - commands:
          - '/interface wireless set [ find name=wlan1 ] comment="new olympus" security-profile=new-olympus ssid=Olympus'
        argument_spec:
          config: [{ comment: 'new olympus', name: wlan1, security_profile: new-olympus, ssid: Olympus }]
          state: replaced
