name: wireless_access_list
package: interface.wireless
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_wireless_access_list
export_command: '/interface wireless access-list export'
resource_class_name: WirelessAccessListResource
documentation:
  module: ros_wireless_access_list
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Wireless Access List Module'
  description:
    - 'This module manages the Wireless Access List configuration of Mikrotik RouterOS network devices.'
  options:
    state:
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        management_protection_key:
          type: str
        private_key:
          type: str
        private_pre_shared_key:
          type: str
        signal_range:
          type: str
          default: '-120..120'
        time:
          type: str
examples:
  - title: 'Using merge state'
    name: 'Merge with device configuration'
    argument_spec:
      config:
        - comment: existing
          signal_range: '-80..120'
        - comment: new
          signal_range: '-50..120'
          interface: wlan1
      state: merged
    before: |
      /interface wireless access-list
      add comment=existing signal-range=-79..120
    after: |
      # RouterOS Output
      #
      /interface wireless access-list
      add comment=existing signal-range=-80..120
      add comment=new interface=wlan1 signal-range=-50..120
    commands:
      - '/interface wireless access-list set [ find comment=existing ] signal-range=-80..120'
      - '/interface wireless access-list add comment=new interface=wlan1 signal-range=-50..120'
resource:
  name: wireless_access_list
  package: interface.wireless
  command: '/interface wireless access-list'
  config_type: config
  keys:
    - comment
  argument_spec:
    states:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
    config:
      type: list
      elements: dict
      options:
        management_protection_key:
          type: str
        private_key:
          type: str
        private_pre_shared_key:
          type: str
        signal_range:
          type: str
          default: '-120..120'
        time:
          type: str
        comment:
          type: str
          required: 'True'
        interface:
          type: str
tests:
  facts:
    name: wireless_access_list
    fixture_contents: |
      # RouterOS Output
      #
      /interface wireless access-list
      add comment=existing signal-range=-79..120
    fixtures:
      - action: add
        values:
          comment: existing
          signal_range: '-79..120'
  unit:
    module_name: ros_wireless_access_list
    fixture_contents: |
      # RouterOS Output
      #
      /interface wireless access-list
      add comment=existing signal-range=-79..120
    tests:
      - commands:
          - '/interface wireless access-list set [ find comment=existing ] signal-range=-80..120'
          - '/interface wireless access-list add comment=new interface=wlan1 signal-range=-50..120'
        argument_spec:
          config: [{ comment: existing, signal_range: '-80..120' }, { comment: new, interface: wlan1, signal_range: '-50..120' }]
          state: merged
