name: wireless_security_profiles
package: interface.wireless
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_wireless_security_profiles
export_command: '/interface wireless security-profiles export'
resource_class_name: WirelessSecurityProfilesResource
documentation:
  module: ros_wireless_security_profiles
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Wireless Security Profiles Module'
  description:
    - 'This module manages the Wireless Security Profiles of Mikrotik RouterOS network devices.'
  options:
    state:
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        authentication_types:
          type: list
examples:
  - title: 'Using merged state'
    name: 'Merge with device configuration'
    argument_spec:
      config:
        - name: test
          supplicant_identity: test
        - name: new
          supplicant_identity: new
      state: merged
    before: |
      /interface wireless security-profiles
      add name=test supplicant-identity=MikroTik
    after: |
      # RouterOS Output
      #
      /interface wireless security-profiles
      add name=test supplicant-identity=test
      add name=new supplicant-identity=new
    commands:
      - '/interface wireless security-profiles set [ find name=test ] supplicant-identity=test'
      - '/interface wireless security-profiles add name=new supplicant-identity=new'
resource:
  name: wireless_security_profiles
  package: interface.wireless
  command: '/interface wireless security-profiles'
  config_type: config
  keys:
    - name
  argument_spec:
    states:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
    config:
      type: list
      elements: dict
      options:
        authentication_types:
          type: list
        name:
          type: str
          required: 'True'
        supplicant_identity:
          type: str
tests:
  facts:
    name: wireless_security_profiles
    fixture_contents: |
      # RouterOS Output
      #
      /interface wireless security-profiles
      add name=test supplicant-identity=MikroTik
    fixtures:
      - action: add
        values:
          name: test
          supplicant_identity: MikroTik
  unit:
    module_name: ros_wireless_security_profiles
    fixture_contents: |
      # RouterOS Output
      #
      /interface wireless security-profiles
      add name=test supplicant-identity=MikroTik
    tests:
      - commands:
          - '/interface wireless security-profiles set [ find name=test ] supplicant-identity=test'
          - '/interface wireless security-profiles add name=new supplicant-identity=new'
        argument_spec:
          config: [{ name: test, supplicant_identity: test }, { name: new, supplicant_identity: new }]
          state: merged
