name: bridge_settings
package: interface.bridge
type: setting
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_bridge_settings
export_command: '/interface bridge settings export'
resource_class_name: BridgeSettingsResource
documentation:
  module: ros_bridge_settings
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Bridge Setting Module'
  description:
    - 'This modules manages configuration in submenu `/interface bridge settings`.'
  options:
    state:
      type: str
      choices:
        - present
        - reset
      default: present
      description: 'Set state for this module'
    config:
      type: dict
      description: 'A dictionary of bridge_settings options'
      suboptions:
        allow_fast_path:
          type: bool
          default: 'True'
          description: 'Whether to enable a bridge L(FastPath, https://wiki.mikrotik.com/wiki/Manual:Fast_Path) globally.'
        use_ip_firewall:
          type: bool
          default: 'False'
          description: |
            Force bridged traffic to also be processed by prerouting, forward and postrouting sections of IP routing (L(Packet Flow,
            https://wiki.mikrotik.com/wiki/Manual:Packet_Flow_v6) to traffic in a bridge. Property use-ip-firewall-for-vlan is required in case bridge
            vlan-filtering is used.
        use_ip_firewall_for_pppoe:
          type: bool
          default: 'False'
          description: |
            Send bridged un-encrypted PPPoE traffic to also be processed by L(IP/Firewall, https://wiki.mikrotik.com/wiki/Manual:IP/Firewall) to PPPoE
            traffic in a bridge.
        use_ip_firewall_for_vlan:
          type: bool
          default: 'False'
          description: |
            Send bridged VLAN traffic to also be processed by L(IP/Firewall, https://wiki.mikrotik.com/wiki/Manual:IP/Firewall) to VLAN traffic in a
            bridge.
examples:
  - title: 'Change Bridge Setting Configuration'
    name: 'Configure Bridge Settings'
    argument_spec:
      config:
        allow_fast_path: 'yes'
        use_ip_firewall: 'no'
        use_ip_firewall_for_pppoe: 'no'
        use_ip_firewall_for_vlan: 'no'
      state: present
    before: |
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    after: |
      # RouterOS Output
      #
      /interface bridge settings
      set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no
    commands:
      - '/interface bridge settings set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no'
  - title: 'Change Bridge Setting Configuration'
    name: 'Configure Bridge Settings'
    argument_spec:
      state: reset
    before: |
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    after: |
      # RouterOS Output
      #
      /interface bridge settings
      set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no
    commands:
      - '/interface bridge settings set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no'
resource:
  name: bridge_settings
  package: interface.bridge
  command: '/interface bridge settings'
  config_type: setting
  keys:
    - name
  supports:
    - export-verbose-mode
  argument_spec:
    state:
      type: str
      choices:
        - present
        - reset
      default: present
    config:
      type: dict
      options:
        allow_fast_path:
          type: bool
          default: 'True'
          description: '(need to be defined later)'
        use_ip_firewall:
          type: bool
          default: 'False'
          description: '(need to be defined later)'
        use_ip_firewall_for_pppoe:
          type: bool
          default: 'False'
          description: '(need to be defined later)'
        use_ip_firewall_for_vlan:
          type: bool
          default: 'False'
          description: '(need to be defined later)'
tests:
  facts:
    name: bridge_settings
    type: setting
    package: interface.bridge
    fixture_contents: |
      # RouterOS Output
      #
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    fixtures:
      - action: set
        values:
          allow_fast_path: 'no'
          use_ip_firewall: 'yes'
          use_ip_firewall_for_pppoe: 'yes'
          use_ip_firewall_for_vlan: 'yes'
  unit:
    name: bridge_settings
    package: interface.bridge
    module_name: ros_bridge_settings
    fixture_contents: |
      # RouterOS Output
      #
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    tests:
      - commands:
          - '/interface bridge settings set allow-fast-path=yes use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no use-ip-firewall=no'
        argument_spec:
          config:
            allow_fast_path: 'yes'
            use_ip_firewall: 'no'
            use_ip_firewall_for_pppoe: 'no'
            use_ip_firewall_for_vlan: 'no'
          state: present
      - commands:
          - '/interface bridge settings set allow-fast-path=yes use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no use-ip-firewall=no'
        argument_spec:
          state: reset
