name: bridge_settings
package: interface.bridge
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_bridge_settings
export_command: '/interface bridge settings export'
resource_class_name: BridgeSettingsResource
documentation:
  module: ros_bridge_settings
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Bridge Setting Module'
  description:
    - 'This modules manages configuration in submenu `/interface bridge settings`.'
  ignores:
    - bridge-fast-path-active
    - bridge-fast-path-packets
    - bridge-fast-path-bytes
    - bridge-fast-forward-packets
    - bridge-fast-forward-bytes
  supports:
    - export-verbose-mode
  options:
    state:
      choices:
        - present
        - reset
      default: present
      description: 'Set state for this module'
    config:
      type: dict
      suboptions:
        allow_fast_path:
          type: bool
          default: 'True'
          description: 'Whether to enable a bridge [ FastPath](https://wiki.mikrotik.com/wiki/Manual:Fast_Path "Manual:Fast Path") globally.'
        comment:
          type: str
          description: 'Short note for bridge_settings resource'
        disabled:
          type: bool
          default: 'False'
          description: 'Set bridge_settings resource disability'
        use_ip_firewall:
          type: bool
          default: 'False'
          description: 'Force bridged traffic to also be processed by prerouting, forward and postrouting sections of IP routing ([ Packet Flow](https://wiki.mikrotik.com/wiki/Manual:Packet_Flow_v6 "Manual:Packet Flow v6")). This does not apply to routed traffic. This property is required in case you want to assign [ Simple Queues](https://wiki.mikrotik.com/wiki/Manual:Queue#Simple_Queues "Manual:Queue") or global [ Queue Tree](https://wiki.mikrotik.com/wiki/Manual:Queue#Queue_Tree "Manual:Queue") to traffic in a bridge. Property <var>use-ip-firewall-for-vlan</var> is required in case bridge <var>vlan-filtering</var> is used.'
        use_ip_firewall_for_pppoe:
          type: bool
          default: 'False'
          description: 'Send bridged un-encrypted PPPoE traffic to also be processed by [ IP/Firewall](https://wiki.mikrotik.com/wiki/Manual:IP/Firewall "Manual:IP/Firewall"). This property only has effect when <var>use-ip-firewall</var> is set to `yes`. This property is required in case you want to assign [ Simple Queues](https://wiki.mikrotik.com/wiki/Manual:Queue#Simple_Queues "Manual:Queue") or global [ Queue Tree](https://wiki.mikrotik.com/wiki/Manual:Queue#Queue_Tree "Manual:Queue") to PPPoE traffic in a bridge.'
        use_ip_firewall_for_vlan:
          type: bool
          default: 'False'
          description: 'Send bridged VLAN traffic to also be processed by [ IP/Firewall](https://wiki.mikrotik.com/wiki/Manual:IP/Firewall "Manual:IP/Firewall"). This property only has effect when <var>use-ip-firewall</var> is set to `yes`. This property is required in case you want to assign [ Simple Queues](https://wiki.mikrotik.com/wiki/Manual:Queue#Simple_Queues "Manual:Queue") or global [ Queue Tree](https://wiki.mikrotik.com/wiki/Manual:Queue#Queue_Tree "Manual:Queue") to VLAN traffic in a bridge.'
examples:
  - title: 'Change Bridge Setting Configuration'
    name: 'Configure Bridge Settings'
    argument_spec:
      config:
        allow_fast_path:
          - 'yes'
        use_ip_firewall:
          - 'no'
        use_ip_firewall_for_pppoe:
          - 'no'
        use_ip_firewall_for_vlan:
          - 'no'
      state: present
    before: |
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    after: |
      /interface bridge settings
      set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no
    commands:
      - '/interface bridge settings set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no'
  - title: 'Change Bridge Setting Configuration'
    name: 'Configure Bridge Settings'
    argument_spec:
      state: reset
    before: |
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    after: |
      /interface bridge settings
      set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no
    commands:
      - '/interface bridge settings set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no'
resource:
  name: bridge_settings
  package: interface.bridge
  command: '/interface bridge settings'
  config_type: setting
  keys:
    - name
  supports:
    - export-verbose-mode
  argument_spec:
    states:
      type: str
      choices:
        - present
        - reset
      default: present
    config:
      type: dict
      options:
        allow_fast_path:
          type: bool
          default: 'True'
        comment:
          type: str
        disabled:
          type: bool
          default: 'False'
        use_ip_firewall:
          type: bool
          default: 'False'
        use_ip_firewall_for_pppoe:
          type: bool
          default: 'False'
        use_ip_firewall_for_vlan:
          type: bool
          default: 'False'
