name: bridge_settings
package: interface.bridge
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_bridge_settings
export_command: '/interface bridge settings export'
resource_class_name: BridgeSettingsResource
documentation:
  module: ros_bridge_settings
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Bridge Setting Module'
  description:
    - 'This modules manages configuration in submenu `/interface bridge settings`.'
  ignores:
    - bridge-fast-path-active
    - bridge-fast-path-packets
    - bridge-fast-path-bytes
    - bridge-fast-forward-packets
    - bridge-fast-forward-bytes
  supports:
    - export-verbose-mode
  options:
    state:
      choices:
        - present
        - reset
      default: present
      description: 'Set state for this module'
    config:
      type: dict
      suboptions:
        allow_fast_path:
          type: bool
          default: 'True'
        comment:
          type: str
        disabled:
          type: bool
          default: 'False'
        use_ip_firewall:
          type: bool
          default: 'False'
        use_ip_firewall_for_pppoe:
          type: bool
          default: 'False'
        use_ip_firewall_for_vlan:
          type: bool
          default: 'False'
examples:
  - title: 'Change Bridge Setting Configuration'
    name: 'Configure Bridge Settings'
    argument_spec:
      config:
        allow_fast_path:
          - 'yes'
        use_ip_firewall:
          - 'no'
        use_ip_firewall_for_pppoe:
          - 'no'
        use_ip_firewall_for_vlan:
          - 'no'
      state: present
    before: |
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    after: |
      /interface bridge settings
      set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no
    commands:
      - '/interface bridge settings set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no'
  - title: 'Change Bridge Setting Configuration'
    name: 'Configure Bridge Settings'
    argument_spec:
      state: reset
    before: |
      /interface bridge settings
      set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    after: |
      /interface bridge settings
      set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no
    commands:
      - '/interface bridge settings set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no'
resource:
  name: bridge_settings
  package: interface.bridge
  command: '/interface bridge settings'
  config_type: setting
  keys:
    - name
  supports:
    - export-verbose-mode
  argument_spec:
    states:
      type: str
      choices:
        - present
        - reset
      default: present
    config:
      type: dict
      options:
        allow_fast_path:
          type: bool
          default: 'True'
        comment:
          type: str
        disabled:
          type: bool
          default: 'False'
        use_ip_firewall:
          type: bool
          default: 'False'
        use_ip_firewall_for_pppoe:
          type: bool
          default: 'False'
        use_ip_firewall_for_vlan:
          type: bool
          default: 'False'
