name: bridge
package: interface.bridge
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_bridge
export_command: '/interface bridge export'
resource_class_name: BridgeResource
documentation:
  module: ros_bridge
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'Bridge Resource Module'
  description:
    - 'This modules manages configuration in submenu `/interface bridge`.'
  options:
    state:
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        disabled:
          type: bool
          default: 'False'
        igmp_version:
          type: int
        mld_version:
          type: int
          default: 1
        mtu:
          type: str
          default: auto
        name:
          type: str
          required: 'True'
examples:
  - title: 'Using Merged'
    name: 'Merge configuration with device configuration'
    argument_spec:
      config:
        - name: br-wan
          comment: 'updated comment'
          arp: enabled
        - name: br-trunk
          comment: 'updated comment'
          arp: enabled
          vlan_filtering: 'yes'
      state: merged
    before: |
      /interface bridge
      add arp=reply-only comment="trunk bridge" name=br-trunk
      add arp=reply-only comment="wan bridge" name=br-wan
    after: |
      # RouterOS Output
      #
      /interface bridge
      add arp=enabled comment="updated comment" name=br-wan
      add arp=enabled comment="updated comment" name=br-trunk vlan-filtering=yes
    commands:
      - '/interface bridge set [ find name=br-wan ] arp=enabled comment="updated comment"'
      - '/interface bridge set [ find name=br-trunk ] arp=enabled comment="updated comment" vlan-filtering=yes'
  - title: 'Using Replaced'
    name: 'Replace device configuration'
    argument_spec:
      config:
        - name: br-wan
          comment: 'replaced comment'
        - name: br-trunk
          comment: 'replaced comment'
      state: replaced
    before: |
      /interface bridge
      add arp=reply-only comment="trunk bridge" name=br-trunk
      add arp=reply-only comment="wan bridge" name=br-wan
    after: |
      # RouterOS Output
      #
      /interface bridge
      add arp=enabled comment="replaced comment" name=br-wan
      add arp=enabled comment="replaced comment" name=br-trunk
    commands:
      - '/interface bridge set [ find name=br-wan ] arp=enabled comment="replaced comment"'
      - '/interface bridge set [ find name=br-trunk ] arp=enabled comment="replaced comment"'
  - title: 'Using Overridden'
    name: 'Override bridge configuration'
    argument_spec:
      config:
        - comment: 'new bridge'
          name: br-new
      state: overridden
    before: |
      /interface bridge
      add arp=reply-only comment="trunk bridge" name=br-trunk
      add arp=reply-only comment="wan bridge" name=br-wan
    after: |
      # RouterOS Output
      #
      /interface bridge
      add comment="new bridge" name=br-new
    commands:
      - '/interface bridge remove name=br-trunk'
      - '/interface bridge remove name=br-wan'
      - '/interface bridge add comment="new bridge" name=br-new'
      - '/system script run ansible-remove-invalid'
  - title: 'Using deleted state'
    name: 'Delete bridge'
    argument_spec:
      config:
        - name: br-trunk
        - name: br-wan
      state: deleted
    before: |
      /interface bridge
      add arp=reply-only comment="trunk bridge" name=br-trunk
      add arp=reply-only comment="wan bridge" name=br-wan
    after: |
      # RouterOS Output
      #
      /interface bridge
    commands:
      - '/interface bridge remove name=br-trunk'
      - '/interface bridge remove name=br-wan'
      - '/system script run ansible-remove-invalid'
resource:
  name: bridge
  package: interface.bridge
  command: '/interface bridge'
  config_type: config
  keys:
    - name
  argument_spec:
    states:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
    config:
      type: list
      elements: dict
      options:
        disabled:
          type: bool
          default: 'False'
        igmp_version:
          type: int
        mld_version:
          type: int
          default: 1
        mtu:
          type: str
          default: auto
        name:
          type: str
          required: 'True'
        arp:
          type: str
        comment:
          type: str
        vlan_filtering:
          type: str
tests:
  facts:
    name: bridge
    fixture_contents: |
      # RouterOS Output
      #
      /interface bridge
      add arp=reply-only comment="trunk bridge" name=br-trunk
      add arp=reply-only comment="wan bridge" name=br-wan
    fixtures:
      - action: add
        values:
          arp: reply-only
          comment: 'trunk bridge'
          name: br-trunk
      - action: add
        values:
          arp: reply-only
          comment: 'wan bridge'
          name: br-wan
  unit:
    module_name: ros_bridge
    fixture_contents: |
      # RouterOS Output
      #
      /interface bridge
      add arp=reply-only comment="trunk bridge" name=br-trunk
      add arp=reply-only comment="wan bridge" name=br-wan
    tests:
      - commands:
          - '/interface bridge set [ find name=br-wan ] arp=enabled comment="updated comment"'
          - '/interface bridge set [ find name=br-trunk ] arp=enabled comment="updated comment" vlan-filtering=yes'
        argument_spec:
          config: [{ arp: enabled, comment: 'updated comment', name: br-wan }, { arp: enabled, comment: 'updated comment', name: br-trunk, vlan_filtering: 'yes' }]
          state: merged
      - commands:
          - '/interface bridge set [ find name=br-wan ] arp=enabled comment="replaced comment"'
          - '/interface bridge set [ find name=br-trunk ] arp=enabled comment="replaced comment"'
        argument_spec:
          config: [{ comment: 'replaced comment', name: br-wan }, { comment: 'replaced comment', name: br-trunk }]
          state: replaced
      - commands:
          - '/interface bridge remove [ find name=br-trunk ]'
          - '/interface bridge remove [ find name=br-wan ]'
          - '/interface bridge add comment="new bridge" name=br-new'
          - '/system script run ansible-remove-invalid'
        argument_spec:
          config: [{ comment: 'new bridge', name: br-new }]
          state: overridden
      - commands:
          - '/interface bridge remove [ find name=br-trunk ]'
          - '/interface bridge remove [ find name=br-wan ]'
          - '/system script run ansible-remove-invalid'
        argument_spec:
          config: [{ name: br-trunk }, { name: br-wan }]
          state: deleted
