name: wireless_access_list
package: interface.wireless
version_added: 1.0.0
author: 'Anthonius Munthi (@kilip)'
module_name: kilip.routeros.ros_wireless_access_list
short_description: 'Wireless Access List Module'
description:
  - 'This module manages the Wireless Access List configuration of Mikrotik RouterOS network devices.'
keys:
  - comment
fixtures:
  - action: add
    values:
      comment: existing
      signal_range: '-79..120'
examples:
  merged:
    title: 'Using merge state'
    name: 'Merge with device configuration'
    argument_spec:
      config:
        - comment: existing
          signal_range: '-80..120'
        - comment: new
          signal_range: '-50..120'
          interface: wlan1
      state: merged
    verify:
      - action: set
        values:
          comment: existing
          signal_range: '-80..120'
      - action: add
        values:
          comment: new
          interface: wlan1
          signal_range: '-50..120'
