name: wireless_cap
package: interface.wireless
version_added: 1.0.0
type: setting
author: 'Anthonius Munthi (@kilip)'
module_name: kilip.routeros.ros_wireless_cap
short_description: 'Wireless CAP Setting'
description:
  - 'This module manages the Wireless CAP setting of Mikrotik RouterOS network devices.'
supports:
  - export-verbose-mode
states:
  - present
  - reset
default_state: present
fixtures:
  - action: set
    values:
      bridge: none
      certificate: none
      enabled: 'no'
      lock_to_caps_man: 'no'
      static_virtual: 'no'
examples:
  present:
    title: 'Change Wireless CAP Setting'
    name: 'Configure Wireless CAP'
    argument_spec:
      config:
        interfaces:
          - wlan1
          - wlan2
      state: present
    verify:
      - action: set
        values:
          interfaces: 'wlan1,wlan2'
