name: capsman_channel
package: capsman
version_added: 1.0.0
author: 'Anthonius Munthi (@kilip)'
module_name: kilip.routeros.ros_capsman_channel
short_description: 'CAPsMan Channels Configuration Module'
description:
  - 'This modules manages CAPsMan Channels configuration on Mikrotik RouterOS network devices'
keys:
  - name
fixtures:
  - action: add
    values:
      name: test
examples:
  merged:
    title: 'Using merged'
    name: 'Merge with device configuration'
    argument_spec:
      config:
        - name: test
          save_selected: 'no'
        - name: new
          extension_channel: Ce
      state: merged
    verify:
      - action: set
        values:
          name: test
          save_selected: 'no'
      - action: add
        values:
          extension_channel: Ce
          name: new
