name: bridge_settings
package: interface.bridge
type: setting
command: '/interface bridge settings'
keys:
  - name
properties:
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short note for bridge_settings resource'
    original_name: comment
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set bridge_settings resource disability'
    original_name: disabled
