name: bridge_port
package: interface.bridge
type: config
command: '/interface bridge port'
keys:
  - bridge
  - interface
properties:
  auto_isolate:
    name: auto_isolate
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'When enabled, prevents a port moving from discarding into forwarding state if no BPDUs are received from the neighboring bridge. The port will change into a forwarding state only when a BPDU is received. This property only has an effect when protocol-mode is set to `rstp` or `mstp` and edge is set to `no`.'
    original_name: auto-isolate
    elements: null
  bpdu_guard:
    name: bpdu_guard
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Enables or disables BPDU Guard feature on a port. This feature puts the port in a disabled role if it receives a BPDU and requires the port to be manually disabled and enabled if a BPDU was received. Should be used to prevent a bridge from BPDU related attacks. This property has no effect when protocol-mode is set to `none`.'
    original_name: bpdu-guard
    elements: null
  bridge:
    name: bridge
    type: string
    required: false
    default: none
    choice_type: null
    description: 'The bridge interface the respective interface is grouped in.'
    original_name: bridge
    elements: null
  broadcast_flood:
    name: broadcast_flood
    type: string
    required: false
    default: 'yes'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'When enabled, bridge floods broadcast traffic to all bridge egress ports. When disabled, drops broadcast traffic on egress ports. Can be used to filter all broadcast traffic on an egress port. Broadcast traffic is considered as traffic that uses **FF:FF:FF:FF:FF:FF** as destination MAC address, such traffic is crucial for many protocols such as DHCP, ARP, NDP, BOOTP (Netinstall) and others. This option does not limit traffic flood to the CPU.'
    original_name: broadcast-flood
    elements: null
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short note for bridge_port resource'
    original_name: comment
    elements: null
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set bridge port disability'
    original_name: disabled
    elements: null
  edge:
    name: edge
    type: string
    required: false
    default: auto
    choices:
      - auto
      - 'no'
      - no-discover
      - 'yes'
      - yes-discover
    choice_type: null
    description: |
      Set port as edge port or non-edge port, or enable edge discovery. Edge ports are connected to a LAN that has no other bridges attached. An edge port will skip the learning and the listening states in STP and will transition directly to the forwarding state, this reduces the STP initialization time. If the port is configured to discover edge port then as soon as the bridge detects a BPDU coming to an edge port, the port becomes a non-edge port. This property has no effect when protocol-mode is set to `none`.
      
      - `no` - non-edge port, will participate in learning and listening states in STP.
      - `no-discover` - non-edge port with enabled discovery, will participate in learning and listening states in STP, a port can become edge port if no BPDU is received.
      - `yes` - edge port without discovery, will transit directly to forwarding state.
      - `yes-discover` - edge port with enabled discovery, will transit directly to forwarding state.
      - `auto` - same as `no-discover`, but will additionally detect if bridge port is a Wireless interface with disabled bridge-mode, such interface will be automatically set as an edge port without discovery.
    original_name: edge
    elements: null
  external_fdb:
    name: external_fdb
    type: string
    required: false
    default: auto
    choices:
      - auto
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Whether to use wireless registration table to speed up bridge host learning. If there are no Wireless interfaces in a bridge, then setting external-fdb to `yes` will disable MAC learning and the bridge will act as a hub (disables hardware offloading). Replaced with learn parameter in RouterOS v6.42'
    original_name: external-fdb
    elements: null
  fast_leave:
    name: fast_leave
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Enables IGMP Fast leave feature on the port. Bridge will stop forwarding traffic to a bridge port whenever a IGMP Leave message is received for appropriate multicast stream. This property only has effect when igmp-snooping is set to `yes`.'
    original_name: fast-leave
    elements: null
  frame_types:
    name: frame_types
    type: string
    required: false
    default: admit-all
    choices:
      - admit-all
      - admit-only-untagged-and-priority-tagged
      - admit-only-vlan-tagged
    choice_type: null
    description: 'Specifies allowed ingress frame types on a bridge port. This property only has effect when vlan-filtering is set to `yes`.'
    original_name: frame-types
    elements: null
  horizon:
    name: horizon
    type: integer
    required: false
    default: 0
    choice_type: null
    description: 'Use split horizon bridging to prevent bridging loops. Set the same value for group of ports, to prevent them from sending data to ports with the same horizon value. Split horizon is a software feature that disables hardware offloading. Read more about [Bridge split horizon](https://wiki.mikrotik.com/wiki/MPLSVPLS#Split_horizon_bridging "MPLSVPLS").'
    original_name: horizon
    elements: null
  ingress_filtering:
    name: ingress_filtering
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Enables or disables VLAN ingress filtering, which checks if the ingress port is a member of the received VLAN ID in the bridge VLAN table. Should be used with frame-types to specify if the ingress traffic should be tagged or untagged. This property only has effect when vlan-filtering is set to `yes`.'
    original_name: ingress-filtering
    elements: null
  interface:
    name: interface
    type: string
    required: false
    default: none
    choice_type: null
    description: 'Name of the interface.'
    original_name: interface
    elements: null
  internal_path_cost:
    name: internal_path_cost
    type: integer
    required: false
    default: 10
    choice_type: null
    description: 'Path cost to the interface for MSTI0 inside a region. This property only has effect when protocol-mode is set to `mstp`.'
    original_name: internal-path-cost
    elements: null
  learn:
    name: learn
    type: string
    required: false
    default: auto
    choices:
      - auto
      - 'no'
      - 'yes'
    choice_type: null
    description: |
      Changes MAC learning behaviour on a bridge port
      
      - `yes` - enables MAC learning
      - `no` - disables MAC learning
      - `auto` - detects if bridge port is a Wireless interface and uses Wireless registration table instead of MAC learning, will use Wireless registration table if the [Wireless interface](https://wiki.mikrotik.com/wiki/Manual:Interface/Wireless "Manual:Interface/Wireless") is set to one of ap-bridge,bridge,wds-slave mode and bridge mode for the [Wireless interface](https://wiki.mikrotik.com/wiki/Manual:Interface/Wireless "Manual:Interface/Wireless") is disabled.
    original_name: learn
    elements: null
  multicast_router:
    name: multicast_router
    type: string
    required: false
    default: temporary-query
    choices:
      - disabled
      - permanent
      - temporary-query
    choice_type: null
    description: |
      Changes the state of a bridge port whether IGMP membership reports are going to be forwarded to this port. By default IGMP membership reports (most importantly IGMP Join messages) are only forwarded to ports that have a multicast router or a IGMP Snooping enabled bridge connected to. Without at least one port marked as a `multicast-router` IPTV might not work properly, it can be either detected automatically or forced manually.
      
      - `disabled` - IGMP membership reports are not forwarded through this port regardless what is connected to it.
      - `permanent` - IGMP membership reports are forwarded through this port regardless what is connected to it.
      - `temporary-query` - automatically detect multicast routers and IGMP Snooping enabled bridges.
      
      You can improve security by forcing ports that have IPTV boxes connected to never become ports marked as `multicast-router`. This property only has effect when igmp-snooping is set to `yes`.
    original_name: multicast-router
    elements: null
  path_cost:
    name: path_cost
    type: integer
    required: false
    default: 10
    choice_type: null
    description: 'Path cost to the interface, used by STP to determine the "best" path, used by MSTP to determine "best" path between regions. This property has no effect when protocol-mode is set to `none`.'
    original_name: path-cost
    elements: null
  point_to_point:
    name: point_to_point
    type: string
    required: false
    default: auto
    choices:
      - auto
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Specifies if a bridge port is connected to a bridge using a point-to-point link for faster convergence in case of failure. By setting this property to `yes`, you are forcing the link to be a point-to-point link, which will skip the checking mechanism, which detects and waits BPDUs from other devices from this single link, by setting this property to `no`, you are expecting that a link can receive BPDUs from multiple devices. By setting the property to `yes`, you are significantly improving (R/M)STP convergence time. In general, you should only set this property to `no` if it is possible that another device can be connected between a link, this is mostly relevant to Wireless mediums and Ethernet hubs. If the Ethernet link is full-duplex, `auto` enables point-to-point functionality. And this property has no effect when protocol-mode is set to `none`.'
    original_name: point-to-point
    elements: null
  priority:
    name: priority
    type: integer
    required: false
    default: 128
    choice_type: null
    description: 'The priority of the interface, used by STP to determine the root port, used by MSTP to determine root port between regions.'
    original_name: priority
    elements: null
  pvid:
    name: pvid
    type: integer
    required: false
    default: 1
    choice_type: null
    description: 'Port VLAN ID (pvid) specifies which VLAN the untagged ingress traffic is assigned to. This property only has effect when vlan-filtering is set to `yes`.'
    original_name: pvid
    elements: null
  restricted_role:
    name: restricted_role
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Enable the restricted role on a port, used by STP to forbid a port becoming a root port. This property only has effect when protocol-mode is set to `mstp`.'
    original_name: restricted-role
    elements: null
  restricted_tcn:
    name: restricted_tcn
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Disable topology change notification (TCN) sending on a port, used by STP to forbid network topology changes to propagate. This property only has effect when protocol-mode is set to `mstp`.'
    original_name: restricted-tcn
    elements: null
  tag_stacking:
    name: tag_stacking
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Forces all packets to be treated as untagged packets. Packets on ingress port will be tagged with another VLAN tag regardless if a VLAN tag already exists, packets will be tagged with a VLAN ID that matches the pvid value and will use EtherType that is specified in ether-type. This property only has effect when vlan-filtering is set to `yes`.'
    original_name: tag-stacking
    elements: null
  trusted:
    name: trusted
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'When enabled, it allows to forward DHCP packets towards DHCP server through this port. Mainly used to limit unauthorized servers to provide malicious information for users. This property only has effect when dhcp-snooping is set to `yes`.'
    original_name: trusted
    elements: null
  unknown_multicast_flood:
    name: unknown_multicast_flood
    type: string
    required: false
    default: 'yes'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'When enabled, bridge floods unknown multicast traffic to all bridge egress ports. When disabled, drops unknown multicast traffic on egress ports. Multicast addresses that are in `/interface bridge mdb` are considered as learned multicasts and therefore will not be flooded to all ports. Without IGMP Snooping all multicast traffic will be dropped on egress ports. Has effect only on an egress port. This option does not limit traffic flood to the CPU. Note that local multicast addresses (224.0.0.0/24) are not flooded when unknown-multicast-flood is disabled, as a result some protocols that rely on local multicast addresses might not work properly, such protocols are RIPv2m OSPF, mDNS, VRRP and others. Some protocols do send a IGMP join request and therefore are compatible with IGMP Snooping, some OSPF implementations are compatible with RFC1584, RouterOS OSPF implementation is not compatible with IGMP Snooping. This property should only be used when igmp-snooping is set to `yes`.'
    original_name: unknown-multicast-flood
    elements: null
  unknown_unicast_flood:
    name: unknown_unicast_flood
    type: string
    required: false
    default: 'yes'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'When enabled, bridge floods unknown unicast traffic to all bridge egress ports. When disabled, drops unknown unicast traffic on egress ports. If a MAC address is not learned in `/interface bridge host`, then the traffic is considered as unknown unicast traffic and will be flooded to all ports. MAC address is learnt as soon as a packet on a bridge port is received, then the source MAC address is added to the bridge host table. Since it is required for the bridge to receive at least one packet on the bridge port to learn the MAC address, it is recommended to use static bridge host entries to avoid packets being dropped until the MAC address has been learnt. Has effect only on an egress port. This option does not limit traffic flood to the CPU.'
    original_name: unknown-unicast-flood
    elements: null
