name: bridge
package: interface.bridge
type: config
command: '/interface bridge'
keys:
  - name
properties:
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: null
    original_name: disabled
  igmp_version:
    name: igmp_version
    type: integer
    required: false
    default: null
    choice_type: null
    description: null
    original_name: igmp-version
  mld_version:
    name: mld_version
    type: integer
    required: false
    default: 1
    choice_type: null
    description: null
    original_name: mld-version
  mtu:
    name: mtu
    type: string
    required: false
    default: auto
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: mtu
  name:
    name: name
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: name
