name: bridge_port
package: interface.bridge
type: config
command: '/interface bridge port'
keys:
  - bridge
  - interface
properties:
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set bridge port disability'
    original_name: disabled
