capsman_configuration:
  versionAdded: 1.0.0
  validated: true
  package: capsman
  command: /caps-man configuration
  generator:
    url: https://wiki.mikrotik.com/wiki/Manual:CAPsMAN
    tableIndex: 4
  documentations:
    short_description: CAPsMan Configuration Module
    descriptions:
      - This modules manages CAPsMan Configuration on Mikrotik RouterOS network devices
  options:
    rx_chains:
      type: list
      elements: int
      choices: [0, 1, 2, 3]
      default: [0]
      defaultIgnored: true
    tx_chains:
      type: list
      elements: int
      choices: [0, 1, 2, 3]
      default: [0]
      defaultIgnored: true
    security_authentication_types:
      defaultIgnored: true
      type: list
      elements: str
      choices:
        - wpa-psk
        - wpa2-psk
        - wpa-eap
        - wpa2-eap
    security_encryption:
      type: list
      elements: str
    channel:
      type: str
    channel.width:
      type: str
    datapath:
      type: str
    datapath_bridge:
      type: str
    datapath_interface_list:
      type: str
    datapath_l2mtu:
      type: str
    datapath_mtu:
      type: str
    datapath_openflow_switch:
      type: str
    disconnect_timeout:
      type: str
    distance:
      type: str
    frame_lifetime:
      type: str
    hw_protection_mode:
      type: str
    hw_retries:
      type: str
    mode:
      type: str
      default: ap
    rates:
      type: str
    security_disable_pmkid:
      type: str
    security_eap_radius_accounting:
      type: str

  module:
    supports:
      - reset_value

  tests:
    fixtures:
      caps-man_configuration_export: |
        /caps-man configuration
        add name=test

    facts:
      asserts:
        - self.assertEqual(result[0]["name"], "test")

  examples:
    - title: Using merged
      name: Merge configuration with devie configuration
      argument_spec:
        state: merged
        config:
          - name: test
            datapath_bridge: br-trunk
            rx_chains:
              - 0
              - 1
              - 2
          - name: new
            datapath_bridge: br-trunk
      commands:
        - /caps-man configuration set [ find name=test ] datapath.bridge=br-trunk rx-chains=0,1,2
        - /caps-man configuration add name=new datapath.bridge=br-trunk
      post: |
        /caps-man configuration
        add name=test datapath.bridge=br-trunk rx-chains=0,1,2
        add name=new datapath.bridge=br-trunk
