name: vlan
package: interface
version_added: 1.0.0
author: 'Anthonius Munthi (@kilip)'
module_name: kilip.routeros.ros_vlan
short_description: 'VLAN Resource Module'
description:
  - 'This module manages the vlan configuration of Mikrotik RouterOS network devices.'
keys:
  - name
fixtures:
  - action: add
    values:
      interface: br-trunk
      name: vlan-100
      vlan_id: '100'
      arp: reply-only
examples:
  merged:
    name: 'Merge configuration with device configuration'
    title: 'Using merged state'
    argument_spec:
      config:
        - name: vlan-100
          interface: br-trunk
          vlan_id: 100
          comment: 'new comment'
        - name: vlan-200
          interface: br-trunk
          vlan_id: 200
          comment: 'new comment'
      state: merged
    verify:
      - action: set
        values:
          name: vlan-100
          arp: enabled
          comment: 'new comment'
      - action: add
        values:
          comment: 'new comment'
          interface: br-trunk
          name: vlan-200
          vlan_id: '200'
  replaced:
    name: 'Replace device configuration'
    title: 'Using replaced state'
    argument_spec:
      config:
        - name: vlan-100
          interface: br-trunk
          vlan_id: 100
          comment: 'new comment'
      state: replaced
    verify:
      - action: set
        values:
          name: vlan-100
          arp: enabled
          comment: 'new comment'
  overridden:
    name: 'Override device configuration'
    title: 'Using overridden state'
    argument_spec:
      config:
        - name: vlan-new
          interface: br-trunk
          vlan_id: 100
          comment: 'new comment'
      state: overridden
    verify:
      - action: remove
        values:
          name: vlan-100
      - action: add
        values:
          comment: 'new comment'
          interface: br-trunk
          name: vlan-new
          vlan_id: '100'
      - action: script
        script: '/system script run ansible-remove-invalid'
  deleted:
    name: 'Delete VLAN Interface'
    title: 'Using deleted state'
    argument_spec:
      config:
        - name: vlan-100
          interface: br-trunk
          vlan_id: 100
      state: deleted
    verify:
      - action: remove
        values:
          name: vlan-100
      - action: script
        script: '/system script run ansible-remove-invalid'
