name: capsman_configuration
package: capsman

command: '/caps-man configuration'
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:CAPsMAN'
  table_index: 4
properties:
  rx_chains:
    type: list
    choices:
      - 0
      - 1
      - 2
      - 3
    options:
      - ignore-default
    defaultValue:
      - 0
  tx_chains:
    type: list
    choices:
      - 0
      - 1
      - 2
      - 3
    options:
      - ignore-default
    defaultValue:
      - 0
  security_authentication_types:
    type: list
    choices:
      - wpa-psk
      - wpa2-psk
      - wpa-eap
      - wpa2-eap
    options:
      - ignore-default
  security_encryption:
    type: list
  channel:
    type: str
  channel_width:
    type: str
  datapath:
    type: str
  datapath_bridge:
    type: str
  datapath_interface_list:
    type: str
  datapath_l2mtu:
    type: str
  datapath_mtu:
    type: str
  datapath_openflow_switch:
    type: str
  disconnect_timeout:
    type: str
  distance:
    type: str
  frame_lifetime:
    type: str
  hw_protection_mode:
    type: str
  hw_retries:
    type: str
  mode:
    type: str
    defaultValue: ap
  rates:
    type: str
  security_disable_pmkid:
    type: str
  security_eap_radius_accounting:
    type: str
