name: capsman_channel
package: capsman

command: '/caps-man channel'
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:CAPsMAN'
  table_index: 5
properties:
  width:
    type: str
  save_selected:
    type: str
    choices:
      - 'yes'
      - 'no'
