name: capsman_manager
package: capsman

command: '/caps-man manager'
type: setting
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:CAPsMAN'
  table_index: 1
properties:
  ca_certificate:
    type: str
    options:
      - ignore-choices
