capsman_configuration:
  package: capsman
  command_root: /caps-man configuration
  validated: true
  generate_test: true
  support_reset_value: true
  generator:
    url: https://wiki.mikrotik.com/wiki/Manual:CAPsMAN
    tableIndex: 4
  key_prefixes:
    - channel
    - datapath
    - rates
    - security
  options:
    security_encryption:
      type: list
      elements: str