name: interface
package: interface


command: /interface
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:Interface'
  table_index: 1
properties:
  disabled:
    type: str
    choices:
      - 'yes'
      - 'no'
    description: 'Set interface disability.'
    defaultValue: 'no'
  mtu:
    type: str
  l2mtu:
    type: str
