name: vlan
package: interface
validated: true
command: '/interface vlan'
properties:
  vlan_id:
    required: true
  interface:
    required: true
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:Interface/VLAN'
  table_index: 0
