name: capsman_manager
package: capsman
type: setting
command: '/caps-man manager'
generator:
  url: 'https://wiki.mikrotik.com/wiki/Manual:CAPsMAN'
  table_index:
    - 1
properties_override:
  ca_certificate:
    type: string
    options:
      - ignore-choices
