name: capsman_configuration
package: capsman
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_capsman_configuration
export_command: '/caps-man configuration export'
resource_class_name: CapsmanConfigurationResource
documentation:
  module: ros_capsman_configuration
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'CAPsMan Configuration Module'
  description:
    - 'This modules manages CAPsMan Configuration on Mikrotik RouterOS network devices'
  supports:
    - reset_value
  options:
    state:
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        channel:
          type: str
        channel_width:
          type: str
        datapath:
          type: str
        datapath_bridge:
          type: str
        datapath_interface_list:
          type: str
        datapath_l2mtu:
          type: str
        datapath_mtu:
          type: str
        datapath_openflow_switch:
          type: str
        disconnect_timeout:
          type: str
        distance:
          type: str
        frame_lifetime:
          type: str
        hw_protection_mode:
          type: str
        hw_retries:
          type: str
        mode:
          type: str
          default: ap
        rates:
          type: str
        rx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        security_authentication_types:
          type: list
          choices: [wpa-psk, wpa2-psk, wpa-eap, wpa2-eap]
        security_disable_pmkid:
          type: str
        security_eap_radius_accounting:
          type: str
        security_encryption:
          type: list
        tx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
examples:
  - title: 'Using merged'
    name: 'Merge configuration with devie configuration'
    argument_spec:
      state: merged
      config:
        - name: test
          datapath_bridge: br-trunk
          rx_chains: '0,1,2'
        - name: new
          datapath_bridge: br-trunk
    before: |
      /caps-man configuration
      add name=test
    after: |
      # RouterOS Output
      #
      /caps-man configuration
      add datapath-bridge=br-trunk name=test rx-chains=0,1,2
      add datapath-bridge=br-trunk name=new
    commands:
      - '/caps-man configuration set [ find name=test ] datapath-bridge=br-trunk rx-chains=0,1,2'
      - '/caps-man configuration add datapath-bridge=br-trunk name=new'
resource:
  name: capsman_configuration
  package: capsman
  command: '/caps-man configuration'
  config_type: config
  keys:
    - name
  supports:
    - reset_value
  argument_spec:
    states:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
    config:
      type: list
      elements: dict
      options:
        channel:
          type: str
        channel_width:
          type: str
        datapath:
          type: str
        datapath_bridge:
          type: str
        datapath_interface_list:
          type: str
        datapath_l2mtu:
          type: str
        datapath_mtu:
          type: str
        datapath_openflow_switch:
          type: str
        disconnect_timeout:
          type: str
        distance:
          type: str
        frame_lifetime:
          type: str
        hw_protection_mode:
          type: str
        hw_retries:
          type: str
        mode:
          type: str
          default: ap
        rates:
          type: str
        rx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        security_authentication_types:
          type: list
          choices: [wpa-psk, wpa2-psk, wpa-eap, wpa2-eap]
        security_disable_pmkid:
          type: str
        security_eap_radius_accounting:
          type: str
        security_encryption:
          type: list
        tx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        name:
          type: str
          required: 'True'
tests:
  facts:
    name: capsman_configuration
    fixture_contents: |
      # RouterOS Output
      #
      /caps-man configuration
      add name=test
    fixtures:
      - action: add
        values:
          name: test
  unit:
    module_name: ros_capsman_configuration
    fixture_contents: |
      # RouterOS Output
      #
      /caps-man configuration
      add name=test
    tests:
      - commands:
          - '/caps-man configuration set [ find name=test ] datapath-bridge=br-trunk rx-chains=0,1,2'
          - '/caps-man configuration add datapath-bridge=br-trunk name=new'
        argument_spec:
          state: merged
          config: [{ datapath_bridge: br-trunk, name: test, rx_chains: '0,1,2' }, { datapath_bridge: br-trunk, name: new }]
