name: capsman_channel
package: capsman
type: config
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_capsman_channel
export_command: '/caps-man channel export'
resource_class_name: CapsmanChannelResource
documentation:
  module: ros_capsman_channel
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'CAPsMan Channels Configuration Module'
  description:
    - 'This modules manages CAPsMan Channels configuration on Mikrotik RouterOS network devices'
  options:
    state:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      description: 'A dictionary of capsman_channel options'
      suboptions:
        band:
          type: str
          choices:
            - 2ghz-b
            - 2ghz-b/g
            - 2ghz-b/g/n
            - 2ghz-onlyg
            - 2ghz-onlyn
            - 5ghz-a
            - 5ghz-a/n
            - 5ghz-onlyn
          description: 'Define operational radio frequency band and mode taken from hardware capability of wireless card'
        comment:
          type: str
          description: 'Short description of the Channel Group profile'
        disabled:
          type: bool
          default: 'False'
          description: 'Set capsman_channel resource disability'
        extension_channel:
          type: str
          choices:
            - Ce
            - Ceee
            - disabled
            - eC
            - eCee
            - eeCe
            - eeeC
          description: 'Extension channel configuration. (E.g. Ce = extension channel is above Control channel, eC = extension channel is below Control channel)'
        frequency:
          type: int
          description: 'Channel frequency value in MHz on which AP will operate.'
        name:
          type: str
          required: 'True'
          description: 'Descriptive name for the Channel Group Profile'
        save_selected:
          type: bool
          default: 'True'
          description: |
            Saves selected channel for the CAP Radio - will select this channel after the CAP reconnects to CAPsMAN and use it till the channel
            Re-optimize is done for this CAP.
        tx_power:
          type: int
          description: |
            TX Power for CAP interface (for the whole interface not for individual chains) in dBm. It is not possible to set higher than allowed by
            country regulations or interface. By default max allowed by country or interface is used.
        width:
          type: str
          description: 'Sets Channel Width in MHz. (E.g. 20, 40)'
examples:
  - title: 'Using merged'
    name: 'Merge with device configuration'
    argument_spec:
      config:
        - name: test
          save_selected: 'no'
        - name: new
          extension_channel: Ce
      state: merged
    before: |
      /caps-man channel
      add name=test
    after: |
      # RouterOS Output
      #
      /caps-man channel
      add name=test save-selected=no
      add extension-channel=Ce name=new
    commands:
      - '/caps-man channel set [ find name=test ] save-selected=no'
      - '/caps-man channel add extension-channel=Ce name=new'
resource:
  name: capsman_channel
  package: capsman
  command: '/caps-man channel'
  config_type: config
  keys:
    - name
  argument_spec:
    state:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
    config:
      type: list
      elements: dict
      options:
        band:
          type: str
          choices:
            - 2ghz-b
            - 2ghz-b/g
            - 2ghz-b/g/n
            - 2ghz-onlyg
            - 2ghz-onlyn
            - 5ghz-a
            - 5ghz-a/n
            - 5ghz-onlyn
          description: '(need to be defined later)'
        comment:
          type: str
          description: '(need to be defined later)'
        disabled:
          type: bool
          default: 'False'
          description: '(need to be defined later)'
        extension_channel:
          type: str
          choices:
            - Ce
            - Ceee
            - disabled
            - eC
            - eCee
            - eeCe
            - eeeC
          description: '(need to be defined later)'
        frequency:
          type: int
          description: '(need to be defined later)'
        name:
          type: str
          required: 'True'
          description: '(need to be defined later)'
        save_selected:
          type: bool
          default: 'True'
          description: '(need to be defined later)'
        tx_power:
          type: int
          description: '(need to be defined later)'
        width:
          type: str
          description: '(need to be defined later)'
tests:
  facts:
    name: capsman_channel
    type: config
    package: capsman
    fixture_contents: |
      # RouterOS Output
      #
      /caps-man channel
      add name=test
    fixtures:
      - action: add
        values:
          name: test
  unit:
    name: capsman_channel
    package: capsman
    module_name: ros_capsman_channel
    fixture_contents: |
      # RouterOS Output
      #
      /caps-man channel
      add name=test
    tests:
      - commands:
          - '/caps-man channel set [ find name=test ] save-selected=no'
          - '/caps-man channel add extension-channel=Ce name=new'
        argument_spec:
          config:
            - { name: test, save_selected: 'no' }
            - { extension_channel: Ce, name: new }
          state: merged
