name: capsman_configuration
package: capsman
template: '@ansible/module/module.py.twig'
module_name: kilip.routeros.ros_capsman_configuration
export_command: '/caps-man configuration export'
resource_class_name: CapsmanConfigurationResource
documentation:
  module: ros_capsman_configuration
  version_added: 1.0.0
  author: 'Anthonius Munthi (@kilip)'
  short_description: 'CAPsMan Configuration Module'
  description:
    - 'This modules manages CAPsMan Configuration on Mikrotik RouterOS network devices'
  supports:
    - reset_value
  options:
    state:
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
      description: 'Set state for this module'
    config:
      type: list
      elements: dict
      suboptions:
        channel:
          type: str
        channel_band:
          type: str
          choices: [2ghz-b, 2ghz-b/g, 2ghz-b/g/n, 2ghz-onlyg, 2ghz-onlyn, 5ghz-a, 5ghz-a/n, 5ghz-a/n/ac, 5ghz-only-ac, 5ghz-onlyn]
        channel_control_channel_width:
          type: str
          choices: [10mhz, 20mhz, 40mhz-turbo, 5mhz]
        channel_extension_channel:
          type: str
          choices: [Ce, Ceee, disabled, eC, eCee, eeCe, eeeC, xx, xxxx]
        channel_frequency:
          type: int
        channel_reselect_interval:
          type: str
        channel_save_selected:
          type: bool
          default: 'False'
        channel_secondary_frequency:
          type: int
          default: 0
        channel_skip_dfs_channels:
          type: bool
          default: 'False'
        channel_tx_power:
          type: int
        channel_width:
          type: str
        comment:
          type: str
        country:
          type: str
          default: no_country_set
        datapath:
          type: str
        datapath_bridge:
          type: str
        datapath_bridge_cost:
          type: int
        datapath_bridge_horizon:
          type: int
        datapath_client_to_client_forwarding:
          type: bool
          default: 'False'
        datapath_interface_list:
          type: str
        datapath_l2mtu:
          type: str
        datapath_local_forwarding:
          type: bool
          default: 'False'
        datapath_mtu:
          type: str
        datapath_openflow_switch:
          type: str
        datapath_vlan_id:
          type: int
        datapath_vlan_mode:
          type: str
          choices: [use-service-tag, use-tag]
        disconnect_timeout:
          type: str
        distance:
          type: str
        frame_lifetime:
          type: str
        guard_interval:
          type: str
          choices: [any, long]
          default: any
        hide_ssid:
          type: bool
        hw_protection_mode:
          type: str
        hw_retries:
          type: str
        installation:
          type: str
          choices: [any, indoor, outdoor]
          default: any
        keepalive_frames:
          type: str
          choices: [disabled, enabled]
          default: enabled
        load_balancing_group:
          type: str
        max_sta_count:
          type: int
        mode:
          type: str
          default: ap
        multicast_helper:
          type: str
          choices: [default, disabled, full]
          default: default
        name:
          type: str
          required: 'True'
        rates:
          type: str
        rates_basic:
          type: str
          choices: [11Mbps, 11Mbps, 12Mbps, 18Mbps, 1Mbps, 24Mbps, 2Mbps, 36Mbps, 48Mbps, 5.5Mbps, 54Mbps, 6Mbps]
        rates_ht_basic_mcs:
          type: list
          choices: [mcs-0, mcs-1, mcs-10, mcs-11, mcs-12, mcs-13, mcs-14, mcs-15, mcs-16, mcs-17, mcs-18, mcs-19, mcs-2, mcs-20, mcs-21, mcs-22, mcs-23, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7, mcs-8, mcs-9]
          default: [mcs-0, mcs-1, mcs-2, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7]
        rates_ht_supported_mcs:
          type: list
          choices: [mcs-0, mcs-1, mcs-10, mcs-11, mcs-12, mcs-13, mcs-14, mcs-15, mcs-16, mcs-17, mcs-18, mcs-19, mcs-2, mcs-20, mcs-21, mcs-22, mcs-23, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7, mcs-8, mcs-9]
          default: [mcs-0, mcs-1, mcs-2, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7, mcs-8, mcs-9, mcs-10, mcs-11, mcs-12, mcs-13, mcs-14, mcs-15, mcs-16, mcs-17, mcs-18, mcs-19, mcs-20, mcs-21, mcs-22, mcs-23]
        rates_supported:
          type: str
          choices: [11Mbps, 11Mbps, 12Mbps, 18Mbps, 1Mbps, 24Mbps, 2Mbps, 36Mbps, 48Mbps, 5.5Mbps, 54Mbps, 6Mbps]
        rates_vht_basic_mcs:
          type: str
          choices: ['MCS 0-7', 'MCS 0-8', 'MCS 0-9', none]
        rates_vht_supported_mcs:
          type: str
          choices: ['MCS 0-7', 'MCS 0-8', 'MCS 0-9', none]
        rx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        security:
          type: str
        security_authentication_types:
          type: list
          choices: [wpa-psk, wpa2-psk, wpa-eap, wpa2-eap]
        security_disable_pmkid:
          type: str
        security_eap_methods:
          type: str
          choices: [eap-tls, passthrough]
        security_eap_radius_accounting:
          type: str
        security_encryption:
          type: list
          choices: [aes-ccm, tkip]
        security_group_encryption:
          type: str
          choices: [aes-ccm, tkip]
          default: aes-ccm
        security_group_key_update:
          type: str
          default: 5m
        security_passphrase:
          type: str
        security_tls_certificate:
          type: str
          choices: [name, none]
        security_tls_mode:
          type: str
          choices: [dont-verify-certificate, no-certificates, verify-certificate, verify-certificate-with-crl]
        ssid:
          type: str
        tx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
examples:
  - title: 'Using merged'
    name: 'Merge configuration with devie configuration'
    argument_spec:
      state: merged
      config:
        - name: test
          datapath_bridge: br-trunk
          rx_chains: '0,1,2'
        - name: new
          datapath_bridge: br-trunk
    before: |
      /caps-man configuration
      add name=test
    after: |
      /caps-man configuration
      add datapath.bridge=br-trunk name=test rx-chains=0,1,2
      add datapath.bridge=br-trunk name=new
    commands:
      - '/caps-man configuration set [ find name=test ] datapath.bridge=br-trunk rx-chains=0,1,2'
      - '/caps-man configuration add datapath.bridge=br-trunk name=new'
resource:
  name: capsman_configuration
  package: capsman
  command: '/caps-man configuration'
  config_type: config
  keys:
    - name
  supports:
    - reset_value
  argument_spec:
    states:
      type: str
      choices:
        - merged
        - replaced
        - overridden
        - deleted
      default: merged
    config:
      type: list
      elements: dict
      options:
        channel:
          type: str
        channel_band:
          type: str
          choices: [2ghz-b, 2ghz-b/g, 2ghz-b/g/n, 2ghz-onlyg, 2ghz-onlyn, 5ghz-a, 5ghz-a/n, 5ghz-a/n/ac, 5ghz-only-ac, 5ghz-onlyn]
        channel_control_channel_width:
          type: str
          choices: [10mhz, 20mhz, 40mhz-turbo, 5mhz]
        channel_extension_channel:
          type: str
          choices: [Ce, Ceee, disabled, eC, eCee, eeCe, eeeC, xx, xxxx]
        channel_frequency:
          type: int
        channel_reselect_interval:
          type: str
        channel_save_selected:
          type: bool
          default: 'False'
        channel_secondary_frequency:
          type: int
          default: 0
        channel_skip_dfs_channels:
          type: bool
          default: 'False'
        channel_tx_power:
          type: int
        channel_width:
          type: str
        comment:
          type: str
        country:
          type: str
          default: no_country_set
        datapath:
          type: str
        datapath_bridge:
          type: str
        datapath_bridge_cost:
          type: int
        datapath_bridge_horizon:
          type: int
        datapath_client_to_client_forwarding:
          type: bool
          default: 'False'
        datapath_interface_list:
          type: str
        datapath_l2mtu:
          type: str
        datapath_local_forwarding:
          type: bool
          default: 'False'
        datapath_mtu:
          type: str
        datapath_openflow_switch:
          type: str
        datapath_vlan_id:
          type: int
        datapath_vlan_mode:
          type: str
          choices: [use-service-tag, use-tag]
        disconnect_timeout:
          type: str
        distance:
          type: str
        frame_lifetime:
          type: str
        guard_interval:
          type: str
          choices: [any, long]
          default: any
        hide_ssid:
          type: bool
        hw_protection_mode:
          type: str
        hw_retries:
          type: str
        installation:
          type: str
          choices: [any, indoor, outdoor]
          default: any
        keepalive_frames:
          type: str
          choices: [disabled, enabled]
          default: enabled
        load_balancing_group:
          type: str
        max_sta_count:
          type: int
        mode:
          type: str
          default: ap
        multicast_helper:
          type: str
          choices: [default, disabled, full]
          default: default
        name:
          type: str
          required: 'True'
        rates:
          type: str
        rates_basic:
          type: str
          choices: [11Mbps, 11Mbps, 12Mbps, 18Mbps, 1Mbps, 24Mbps, 2Mbps, 36Mbps, 48Mbps, 5.5Mbps, 54Mbps, 6Mbps]
        rates_ht_basic_mcs:
          type: list
          choices: [mcs-0, mcs-1, mcs-10, mcs-11, mcs-12, mcs-13, mcs-14, mcs-15, mcs-16, mcs-17, mcs-18, mcs-19, mcs-2, mcs-20, mcs-21, mcs-22, mcs-23, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7, mcs-8, mcs-9]
          default: [mcs-0, mcs-1, mcs-2, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7]
        rates_ht_supported_mcs:
          type: list
          choices: [mcs-0, mcs-1, mcs-10, mcs-11, mcs-12, mcs-13, mcs-14, mcs-15, mcs-16, mcs-17, mcs-18, mcs-19, mcs-2, mcs-20, mcs-21, mcs-22, mcs-23, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7, mcs-8, mcs-9]
          default: [mcs-0, mcs-1, mcs-2, mcs-3, mcs-4, mcs-5, mcs-6, mcs-7, mcs-8, mcs-9, mcs-10, mcs-11, mcs-12, mcs-13, mcs-14, mcs-15, mcs-16, mcs-17, mcs-18, mcs-19, mcs-20, mcs-21, mcs-22, mcs-23]
        rates_supported:
          type: str
          choices: [11Mbps, 11Mbps, 12Mbps, 18Mbps, 1Mbps, 24Mbps, 2Mbps, 36Mbps, 48Mbps, 5.5Mbps, 54Mbps, 6Mbps]
        rates_vht_basic_mcs:
          type: str
          choices: ['MCS 0-7', 'MCS 0-8', 'MCS 0-9', none]
        rates_vht_supported_mcs:
          type: str
          choices: ['MCS 0-7', 'MCS 0-8', 'MCS 0-9', none]
        rx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
        security:
          type: str
        security_authentication_types:
          type: list
          choices: [wpa-psk, wpa2-psk, wpa-eap, wpa2-eap]
        security_disable_pmkid:
          type: str
        security_eap_methods:
          type: str
          choices: [eap-tls, passthrough]
        security_eap_radius_accounting:
          type: str
        security_encryption:
          type: list
          choices: [aes-ccm, tkip]
        security_group_encryption:
          type: str
          choices: [aes-ccm, tkip]
          default: aes-ccm
        security_group_key_update:
          type: str
          default: 5m
        security_passphrase:
          type: str
        security_tls_certificate:
          type: str
          choices: [name, none]
        security_tls_mode:
          type: str
          choices: [dont-verify-certificate, no-certificates, verify-certificate, verify-certificate-with-crl]
        ssid:
          type: str
        tx_chains:
          type: list
          choices: [0, 1, 2, 3]
          default: [0]
  custom_props:
    channel_band:
      original_name: channel.band
    channel_control_channel_width:
      original_name: channel.control-channel-width
    channel_extension_channel:
      original_name: channel.extension-channel
    channel_frequency:
      original_name: channel.frequency
    channel_reselect_interval:
      original_name: channel.reselect-interval
    channel_save_selected:
      original_name: channel.save-selected
    channel_secondary_frequency:
      original_name: channel.secondary-frequency
    channel_skip_dfs_channels:
      original_name: channel.skip-dfs-channels
    channel_tx_power:
      original_name: channel.tx-power
    channel_width:
      original_name: channel.width
    datapath_bridge:
      original_name: datapath.bridge
    datapath_bridge_cost:
      original_name: datapath.bridge-cost
    datapath_bridge_horizon:
      original_name: datapath.bridge-horizon
    datapath_client_to_client_forwarding:
      original_name: datapath.client-to-client-forwarding
    datapath_interface_list:
      original_name: datapath.interface-list
    datapath_l2mtu:
      original_name: datapath.l2mtu
    datapath_local_forwarding:
      original_name: datapath.local-forwarding
    datapath_mtu:
      original_name: datapath.mtu
    datapath_openflow_switch:
      original_name: datapath.openflow-switch
    datapath_vlan_id:
      original_name: datapath.vlan-id
    datapath_vlan_mode:
      original_name: datapath.vlan-mode
    rates_basic:
      original_name: rates.basic
    rates_ht_basic_mcs:
      original_name: rates.ht-basic-mcs
    rates_ht_supported_mcs:
      original_name: rates.ht-supported-mcs
    rates_supported:
      original_name: rates.supported
    rates_vht_basic_mcs:
      original_name: rates.vht-basic-mcs
    rates_vht_supported_mcs:
      original_name: rates.vht-supported-mcs
    security_authentication_types:
      original_name: security.authentication-types
    security_disable_pmkid:
      original_name: security.disable-pmkid
    security_eap_methods:
      original_name: security.eap-methods
    security_eap_radius_accounting:
      original_name: security.eap-radius-accounting
    security_encryption:
      original_name: security.encryption
    security_group_encryption:
      original_name: security.group-encryption
    security_group_key_update:
      original_name: security.group-key-update
    security_passphrase:
      original_name: security.passphrase
    security_tls_certificate:
      original_name: security.tls-certificate
    security_tls_mode:
      original_name: security.tls-mode
