bridge:
  name: bridge
  package: interface.bridge
  resource_class: BridgeResource
  config_file: config/compiled/ansible/interface/bridge/bridge.yaml
bridge_port:
  name: bridge_port
  package: interface.bridge
  resource_class: BridgePortResource
  config_file: config/compiled/ansible/interface/bridge/bridge_port.yaml
bridge_settings:
  name: bridge_settings
  package: interface.bridge
  resource_class: BridgeSettingsResource
  config_file: config/compiled/ansible/interface/bridge/bridge_settings.yaml
capsman_aaa:
  name: capsman_aaa
  package: capsman
  resource_class: CapsmanAaaResource
  config_file: config/compiled/ansible/capsman/capsman_aaa.yaml
capsman_channel:
  name: capsman_channel
  package: capsman
  resource_class: CapsmanChannelResource
  config_file: config/compiled/ansible/capsman/capsman_channel.yaml
capsman_configuration:
  name: capsman_configuration
  package: capsman
  resource_class: CapsmanConfigurationResource
  config_file: config/compiled/ansible/capsman/capsman_configuration.yaml
capsman_datapath:
  name: capsman_datapath
  package: capsman
  resource_class: CapsmanDatapathResource
  config_file: config/compiled/ansible/capsman/capsman_datapath.yaml
capsman_manager:
  name: capsman_manager
  package: capsman
  resource_class: CapsmanManagerResource
  config_file: config/compiled/ansible/capsman/capsman_manager.yaml
capsman_provisioning:
  name: capsman_provisioning
  package: capsman
  resource_class: CapsmanProvisioningResource
  config_file: config/compiled/ansible/capsman/capsman_provisioning.yaml
ethernet:
  name: ethernet
  package: interface
  resource_class: EthernetResource
  config_file: config/compiled/ansible/interface/ethernet.yaml
interface:
  name: interface
  package: interface
  resource_class: InterfaceResource
  config_file: config/compiled/ansible/interface/interface.yaml
vlan:
  name: vlan
  package: interface
  resource_class: VlanResource
  config_file: config/compiled/ansible/interface/vlan.yaml
wireless:
  name: wireless
  package: interface.wireless
  resource_class: WirelessResource
  config_file: config/compiled/ansible/interface/wireless/wireless.yaml
wireless_access_list:
  name: wireless_access_list
  package: interface.wireless
  resource_class: WirelessAccessListResource
  config_file: config/compiled/ansible/interface/wireless/wireless_access_list.yaml
wireless_cap:
  name: wireless_cap
  package: interface.wireless
  resource_class: WirelessCapResource
  config_file: config/compiled/ansible/interface/wireless/wireless_cap.yaml
wireless_connect_list:
  name: wireless_connect_list
  package: interface.wireless
  resource_class: WirelessConnectListResource
  config_file: config/compiled/ansible/interface/wireless/wireless_connect_list.yaml
wireless_security_profiles:
  name: wireless_security_profiles
  package: interface.wireless
  resource_class: WirelessSecurityProfilesResource
  config_file: config/compiled/ansible/interface/wireless/wireless_security_profiles.yaml
