name: wireless_cap
package: interface.wireless
type: setting
command: '/interface wireless cap'
keys:
  - name
properties:
  bridge:
    name: bridge
    type: string
    required: false
    default: none
    choice_type: null
    description: 'Bridge to which interfaces should be added when local forwarding mode is used'
    original_name: bridge
  caps_man_addresses:
    name: caps_man_addresses
    type: list
    required: false
    default: null
    choice_type: null
    description: 'List of Manager IP addresses that CAP will attempt to contact during discovery'
    original_name: caps-man-addresses
  caps_man_certificate_common_names:
    name: caps_man_certificate_common_names
    type: list
    required: false
    default: null
    choice_type: null
    description: 'List of Manager certificate CommonNames that CAP will connect to, if empty - CAP does not check Manager certificate CommonName'
    original_name: caps-man-certificate-common-names
  caps_man_names:
    name: caps_man_names
    type: list
    required: false
    default: null
    choice_type: null
    description: 'An ordered list of CAPs Manager names that the CAP will connect to, if empty - CAP does not check Manager name'
    original_name: caps-man-names
  certificate:
    name: certificate
    type: string
    required: false
    default: none
    choice_type: null
    description: 'Certificate to use for authenticating'
    options:
      - ignore-choices
    original_name: certificate
  discovery_interfaces:
    name: discovery_interfaces
    type: list
    required: false
    default: null
    choice_type: null
    description: 'List of interfaces over which CAP should attempt to discover Manager'
    original_name: discovery-interfaces
  enabled:
    name: enabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: 'Disable or enable CAP feature'
    original_name: enabled
  interfaces:
    name: interfaces
    type: list
    required: false
    default: null
    choice_type: null
    description: 'List of wireless interfaces to be controlled by Manager'
    original_name: interfaces
  lock_to_caps_man:
    name: lock_to_caps_man
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: null
    original_name: lock-to-caps-man
  static_virtual:
    name: static_virtual
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'CAP will create Static Virtual Interfaces instead of Dynamic and will try to reuse the same interface on reconnect to CAPsMAN if the MAC address will be the same. Note if two or more interfaces will have the same MAC address the assignment from the CAPsMAN could be random between those interfaces.'
    original_name: static-virtual
