name: wireless_access_list
package: interface.wireless
type: config
command: '/interface wireless access-list'
keys:
  - comment
properties:
  management_protection_key:
    name: management_protection_key
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: management-protection-key
  private_key:
    name: private_key
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: private-key
  private_pre_shared_key:
    name: private_pre_shared_key
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: private-pre-shared-key
  signal_range:
    name: signal_range
    type: string
    required: false
    default: '-120..120'
    choice_type: null
    description: null
    original_name: signal-range
  time:
    name: time
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-choices
    original_name: time
