name: wireless_security_profiles
package: interface.wireless
type: config
command: '/interface wireless security-profiles'
keys:
  - name
properties:
  authentication_types:
    name: authentication_types
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: authentication-types
