name: wireless_cap
package: interface.wireless
type: setting
command: '/interface wireless cap'
keys:
  - name
properties:
  bridge:
    name: bridge
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: bridge
  caps_man_addresses:
    name: caps_man_addresses
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: caps-man-addresses
  caps_man_certificate_common_names:
    name: caps_man_certificate_common_names
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: caps-man-certificate-common-names
  caps_man_names:
    name: caps_man_names
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: caps-man-names
  certificate:
    name: certificate
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-choices
    original_name: certificate
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short note for wireless_cap resource'
    original_name: comment
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: 'Set wireless_cap resource disability'
    original_name: disabled
  discovery_interfaces:
    name: discovery_interfaces
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: discovery-interfaces
  interfaces:
    name: interfaces
    type: list
    required: false
    default: null
    choice_type: null
    description: null
    original_name: interfaces
  static_virtual:
    name: static_virtual
    type: string
    required: false
    default: 'no'
    choices:
      - 'yes'
      - 'no'
    choice_type: null
    description: null
    original_name: static-virtual
