name: wireless_connect_list
package: interface.wireless
type: config
command: '/interface wireless connect-list'
keys:
  - comment
properties:
  interface:
    name: interface
    type: null
    required: true
    default: null
    choice_type: null
    description: null
    original_name: interface
  signal_range:
    name: signal_range
    type: string
    required: false
    default: '-120..120'
    choice_type: null
    description: null
    original_name: signal-range
  ssid:
    name: ssid
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: ssid
