name: wireless_connect_list
package: interface.wireless
type: config
command: '/interface wireless connect-list'
keys:
  - comment
properties:
  3gpp:
    name: 3gpp
    type: string
    required: false
    default: null
    choice_type: null
    description: ''
    original_name: 3gpp
  area_prefix:
    name: area_prefix
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Rule matches if area value of AP (a proprietary extension) begins with specified value.**area** value is a proprietary extension.'
    original_name: area-prefix
  comment:
    name: comment
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Short description of an entry'
    original_name: comment
  connect:
    name: connect
    type: string
    required: false
    default: 'yes'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: |
      Available options:
      
      - *yes* - Connect to access point that matches this rule.
      - *no* - Do not connect to any access point that matches this rule.
    original_name: connect
  disabled:
    name: disabled
    type: string
    required: false
    default: 'no'
    choices:
      - 'no'
      - 'yes'
    choice_type: null
    description: ''
    original_name: disabled
  interface:
    name: interface
    type: string
    required: true
    default: null
    choice_type: null
    description: 'Each rule in connect list applies only to one wireless interface that is specified by this setting.'
    original_name: interface
  mac_address:
    name: mac_address
    type: string
    required: false
    default: '00:00:00:00:00:00'
    choice_type: null
    description: 'Rule matches only AP with the specified MAC address. Value *00:00:00:00:00:00* matches always.'
    original_name: mac-address
  security_profile:
    name: security_profile
    type: string
    required: false
    default: none
    choice_type: null
    description: 'Name of [ security profile](#Security_Profiles) that is used when connecting to matching access points, If value of this property is *none*, then security profile specified in the interface configuration will be used. In station mode, rule will match only access points that can support specified security profile. Value *none* will match access point that supports security profile that is specified in the interface configuration. In access point mode value of this property will not be used to match remote devices.'
    original_name: security-profile
  signal_range:
    name: signal_range
    type: string
    required: false
    default: '-120..120'
    choice_type: null
    description: 'Rule matches if signal strength of the access point is within the range. If station establishes connection to access point that is matched by this rule, it will disconnect from that access point when signal strength goes out of the specified range.'
    original_name: signal-range
  ssid:
    name: ssid
    type: string
    required: false
    default: null
    choice_type: null
    description: 'Rule matches access points that have this SSID. Empty value matches any SSID. This property has effect only when station mode interface **ssid** is empty, or when access point mode interface has **wds-ignore-ssid**=*yes*'
    options:
      - ignore-default
    original_name: ssid
  wireless_protocol:
    name: wireless_protocol
    type: string
    required: false
    default: any
    choices:
      - '802.11'
      - any
      - nstreme
      - tdma
    choice_type: null
    description: ''
    original_name: wireless-protocol
