name: wireless
package: interface.wireless
type: config
command: '/interface wireless'
keys:
  - name
properties:
  ampdu_priorities:
    name: ampdu_priorities
    type: list
    required: false
    default:
      - 0
    choices:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: ampdu-priorities
  disconnect_timeout:
    name: disconnect_timeout
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: disconnect-timeout
  radio_name:
    name: radio_name
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: radio-name
  rx_chains:
    name: rx_chains
    type: list
    required: false
    default:
      - 0
    choices:
      - 0
      - 1
      - 2
      - 3
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: rx-chains
  scan_list:
    name: scan_list
    type: list
    required: false
    default:
      - default
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: scan-list
  ssid:
    name: ssid
    type: null
    required: false
    default: null
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: ssid
  tx_chains:
    name: tx_chains
    type: list
    required: false
    default:
      - 0
    choices:
      - 0
      - 1
      - 2
      - 3
    choice_type: null
    description: null
    options:
      - ignore-default
    original_name: tx-chains
  update_stats_interval:
    name: update_stats_interval
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: update-stats-interval
  wps_mode:
    name: wps_mode
    type: string
    required: false
    default: null
    choice_type: null
    description: null
    original_name: wps-mode
