bridge_settings:
  versionAdded: 1.0.0
  validated: true
  package: bridge
  command: /interface bridge settings
  type: setting
  documentations:
    short_description: Bridge Setting Module
    descriptions:
      - This modules manages configuration in submenu `/interface bridge settings`.
  module:
    supports: ["facts_verbose_mode"]
    states: ["present", "reset"]
    default_state: present
  generator:
    url: https://wiki.mikrotik.com/wiki/Manual:Interface/Bridge
    tableIndex: 1
    ignores:
      - bridge-fast-path-active
      - bridge-fast-path-packets
      - bridge-fast-path-bytes
      - bridge-fast-forward-packets
      - bridge-fast-forward-bytes
  tests:
    fixtures:
      interface_bridge_settings_export_verbose: |
        # sep/05/2020 03:33:38 by RouterOS 6.47.2
        # software id =
        #
        #
        #
        /interface bridge settings
        set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
    facts:
      asserts:
        - self.assertEqual(result["allow_fast_path"], "no")
        - self.assertEqual(result["use_ip_firewall"], "yes")
        - self.assertEqual(result["use_ip_firewall_for_pppoe"], "yes")
        - self.assertEqual(result["use_ip_firewall_for_vlan"], "yes")
  examples:
    # state: present
    - name: Configure Bridge Settings
      title: Change Bridge Setting Configuration
      argument_spec:
        config:
          allow_fast_path: yes
          use_ip_firewall: no
          use_ip_firewall_for_pppoe: no
          use_ip_firewall_for_vlan: no
        state: present
      commands:
        - /interface bridge settings set allow-fast-path=yes use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no use-ip-firewall=no
      pre: |
        [admin@MikroTik] > /interface bridge settings export verbose
        /interface bridge settings
        set allow-fast-path=no use-ip-firewall=yes use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes
      post: |
        [admin@MikroTik] > /interface bridge settings export verbose
        /interface bridge settings
        set allow-fast-path=yes use-ip-firewall=no use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no

    # state: reset
    - name: Configure Bridge Settings
      title: Change Bridge Setting Configuration
      argument_spec:
        state: reset
      commands:
        - /interface bridge settings set allow-fast-path=yes use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no use-ip-firewall=no
      pre: |
        [admin@MikroTik] > /interface bridge settings export verbose
        /interface bridge settings
        set allow-fast-path=no use-ip-firewall-for-pppoe=yes use-ip-firewall-for-vlan=yes use-ip-firewall=yes
      post: |
        [admin@MikroTik] > /interface bridge settings export verbose
        /interface bridge settings
        set allow-fast-path=yes use-ip-firewall-for-pppoe=no use-ip-firewall-for-vlan=no use-ip-firewall=no